### PR TITLE
Dynamic imports landed in Firefox 66

### PR DESCRIPTION
**Pull request by chicoxyzzy**
https://bugzilla.mozilla.org/show_bug.cgi?id=1342012

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
CI fails on validation. How to add Android versions of Firefox properly?

**Comment by HM100** [comment]
Just remove the Android versions of Firefox 64+. No new browser versions can be added trough PR @chicoxyzzy

**Comment by chicoxyzzy** [comment]
This feature is currently disabled by default so please don't merge this PR yet
https://bugzilla.mozilla.org/show_bug.cgi?id=1517546

**Comment by chicoxyzzy** [comment]
Updated to match https://github.com/mdn/browser-compat-data/pull/3248

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
