### PR TITLE
AVIF coming to Safari & Safari on iOS 16

### PR DESCRIPTION
**Pull request by Schweinepriester**
- https://twitter.com/jaffathecake/status/1540697894683942912
- https://github.com/WebKit/WebKit/pull/1717

Given it's early and not yet [test](https://tests.caniuse.com/avif)able, draft for now.

@jensimmons are you able to comment on this? :)
If you are, do you know or are able to find out about support for AVIF sequences?
See note 2, Firefox doesn't have them yet: https://caniuse.com/avif
Test here: https://tests.caniuse.com/avif

### CODE REVIEW

**Comment by jensimmons** [comment]
Support for AVIF is not in Safari 16 beta 2, so it is too early to make a change on Can I Use.

**Comment by jensimmons** [comment]
AVIF support is in macOS Ventura and iOS 16, and we did just land support for AVIF in WebKit — so support in Safari is on its way!

I'll find out about support for AVIF sequences and let you know.

**Comment by Schweinepriester** [comment]
Interesting development, potentially increasing pressure:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1686338#c28
- https://github.com/AOMediaCodec/av1-avif/pull/86

> Since animated AVIF files [now](https://github.com/AOMediaCodec/av1-avif/pull/86) use the same extension and MIME type as non-animated AVIF images, this bug constitutes an interoperability / web compatibility issue.

See the example there.

@Fyrd: Depending on how that plays out, maybe we should give partial for note 2 (for not supporting AVIF sequences)?

**Comment by jensimmons** [comment]
WebKit's implementation does support image sequence and animations.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
