### PR TITLE
ios 16 and 16.1 still doesn't support AVIF images taht are animated or that have noise synthesis

### PR DESCRIPTION
**Pull request by BuyMyMojo**

### CODE REVIEW

**Comment by Schweinepriester** [comment]
Did you check on Safari on macOS as well? Is it only an issue on mobile?

Also related #6505 - are we not able to find an animated AVIF that works in Safari on iOS/iPadOS? 🤔

**Comment by BuyMyMojo** [comment]
> Did you check on Safari on macOS as well? Is it only an issue on mobile?

I do not have a MacOS device I can easily check on, I'll see what I can do.

> Also related https://github.com/Fyrd/caniuse/issues/6505 - are we not able to find an animated AVIF that works in Safari on iOS/iPadOS? 🤔

I have tried making them in a few programs with the most basic settings to give them the best shot of at least being partially supported but none of them have been able ot load for me.

**Comment by jensimmons** [comment]
Could you please add a description and update the title for this PR, so it's clear what this is about?

**Comment by BuyMyMojo** [comment]
> Could you please add a description and update the title for this PR, so it's clear what this is about?

updated

**Comment by Fyrd** [comment]
@jensimmons Do you dispute these findings at all? If there's any sample files the WebKit/Safari team can share that would also be very helpful.

**Comment by Schweinepriester** [comment]
Same as #6505 I believe, this PR is now already done by https://github.com/Fyrd/caniuse/pull/6557.

**Comment by Fyrd** [comment]
Closing as per last comment

**Pull request closed without merging**
