### PR TITLE
Update iOS 16 support in avif.json

### PR DESCRIPTION
**Pull request by BuyMyMojo**
Add note 2 to iOS 16.

Add no support for noise synthesis as note 4 and attach to iOS 16.

### CODE REVIEW

**Comment by Fyrd** [comment]
Thanks! Is there a sample file somewhere that can be used to test the noise synthesis support?

**Comment by BuyMyMojo** [comment]
> Thanks! Is there a sample file somewhere that can be used to test the noise synthesis support?

Yeah I've attached one here but you can also make one super easily with https://squoosh.app/

In a zip file:
[7-2.zip](https://github.com/Fyrd/caniuse/files/9266011/7-2.zip)

Hosted in my S3 bucket:
https://s3.buymymojo.net/ShareX/2022/08/16/35/7-2.avif

**Comment by BuyMyMojo** [comment]
Here is an animated test file too:

In a zip file:
[TestAnimatedAVIF.zip](https://github.com/Fyrd/caniuse/files/9274879/TestAnimatedAVIF.zip)


Hosted in my S3 bucket:
https://s3.buymymojo.net/ShareX/2022/08/21/00/TestAnimatedAVIF.avif

**Comment by Schweinepriester** [comment]
Is there an issue for not supporting noise synthesis AVIFs on <https://bugs.webkit.org/>?

CC @jensimmons

**Comment by Fyrd** [comment]
Thanks!

**Comment by jensimmons** [comment]
I don't see an issue for this at bugs.wekbit.org. @BuyMyMojo could you please file one?

Also — Safari 16 is in beta, and we are still polishing. It may be too soon to be documenting details in progress on Can I Use.

**Comment by Schweinepriester** [comment]
@BuyMyMojo could you retest with the released iOS 16.0? :)

**Comment by jensimmons** [comment]
Could you also try an image that's not created by Squoosh.

**Comment by BuyMyMojo** [comment]
Still no support as far as I can tell;

---

- [Base image](https://s3.buymymojo.net/ShareX/2022/09/16/10/base.jpg)
- [Squoosh encoded image](https://s3.buymymojo.net/ShareX/2022/09/16/10/squoosh.avif)
- [Libavif encoded image](https://s3.buymymojo.net/ShareX/2022/09/16/11/avifenc.avif)

---

- [Base video](https://s3.buymymojo.net/ShareX/2022/09/16/08/base.mp4)
- [Libavif encoded video](https://s3.buymymojo.net/ShareX/2022/09/16/09/avifenc.avif)
- [FFMPEG encoded video](https://s3.buymymojo.net/ShareX/2022/09/16/09/ffmpeg.avif)

---

**Comment by karlcow** [comment]
Do we know if the results given by https://gpac.github.io/ComplianceWarden-wasm/avif.html are trustable?

**Comment by BuyMyMojo** [comment]
> Do we know if the results given by https://gpac.github.io/ComplianceWarden-wasm/avif.html are trustable?
> 
> 

It seems semi trustworthy but doesn't seem to keep animated AVIF images in mind, recommending still_picture is set to one even though it is animated.

Also has a `Rule 17` error in the encoding of the still AVIF enc image even though that's the official reference tool.

**Comment by gsnedders** [comment]
> Also has a `Rule 17` error in the encoding of the still AVIF enc image even though that's the official reference tool.

This seems accurate; the image is a baseline profile image which has the wrong AV1 level. Sounds like a libavif bug!

**Pull request merged**
