### PR TITLE
padStart()

### PR DESCRIPTION
**Pull request by jhpratt**
#3143

### CODE REVIEW

**Comment by Fyrd** [comment]
Support in Firefox started at v48, not 51, just like for padEnd. Also since the properties are related and support appears to be the same for both, can you combine the two into one? Thanks.

**Comment by jhpratt** [comment]
I was just going off the MSN page, which has it listed as 51. I can combine them if you'd like, but it really doesn't make a difference. I was just trying to keep it one file per PR.

**Comment by Fyrd** [comment]
MDN has great info, but the browser support often has mistakes as it tends to go unverified. Please do your own testing when submitting features. 

Also multiple files does make a difference in various ways, I prefer not making the repo size any larger than it has to be when it can be avoided.

**Comment by jhpratt** [comment]
Just merged the files into one.

What do you use for browser testing? I don't have anything.

**Comment by Fyrd** [comment]
Thanks!

There's some suggested services mentioned under https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#adding-a-feature, or you can find older versions to download and run. Alternatively see if browsers themselves have the info, like chromestatus.com.

**Pull request merged**
