### PR TITLE
Firefox 109 enabled support for CSS Container Queries and Units

### PR DESCRIPTION
**Pull request by shospodarets**
- [Here is the related issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1801123) closed by Firefox Dev team
- [Here is the codepen demo](https://codepen.io/shospodarets/pen/zYaWLLp) tested in Firefox Nightly 109
- Here is the screenshot from the working demo in Firefox: Here is the screenshot from the working demo in Firefox

### CODE REVIEW

**Comment by Schweinepriester** [comment]
While I'm invested in this as well and very much looking forward to it (https://github.com/Fyrd/caniuse/pull/6498 ;)), I'm afraid the current change in [bug 1801123](https://bugzilla.mozilla.org/show_bug.cgi?id=1801123) is for nightly only, see https://hg.mozilla.org/mozilla-central/rev/335d18658070:

```diff
-  value: false
+  value: @IS_NIGHTLY_BUILD@
```

→ I'm afraid as of now your changes are not correct.

We could do something like
`"n #42"`
and the note then stating something like
"Can be enabled by setting `layout.css.container-queries.enabled` to `true` in about:config. Enabled by default in Nightly only."

**Comment by shospodarets** [comment]
I just checked, and the intention is to enable it during 109 version going towards the stable channel.
I propose to go a simple way- let’s wait until 109 goes to Dev and towards stable (so “nightly” removed), and merge if all looks right,
or I will decline otherwise.

**Comment by Schweinepriester** [comment]
Very fair!

To improve my process: How did you check?

**Comment by shospodarets** [comment]
> Very fair!
> 
> To improve my process: How did you check?

By asking the team working on FF 😉

**Comment by Fyrd** [comment]
Thanks!

**Comment by shospodarets** [comment]
@Schweinepriester you appeared to be right, the FF team didn't change the "IF NIGHTLY" previous time due to a few found issues, so they moved the support enablement into version 110 🤷‍♂️🙂.
PR [is here](https://github.com/Fyrd/caniuse/pull/6567)

**Pull request merged**
