### PR TITLE
Safari & iOS Safari 14: WebP, HTTP/3, BigInt, image-orientation and Picture-in-Picture 🎉

### PR DESCRIPTION
**Pull request by Schweinepriester**
Once Safari & iOS Safari 14 are available (#5483), this PR should be ready to go.

~Currently WIP~ Done i think.

### CODE REVIEW

**Comment by kiding** [comment]
Just for the reference: Here's a link to [Safari 14 Beta Release Notes]9https://developer.apple.com/documentation/safari-release-notes/safari-14-beta-release-notes)

**Comment by Fyrd** [comment]
Thanks for the quick updates @Schweinepriester !

**Comment by Schweinepriester** [comment]
Sure :)

For the record: I changed TP as well, despite that to my knowledge a new version (109?) with those features is not yet available. But I think we can be safely assume one is coming shortly.

**Comment by Schweinepriester** [comment]
There we go: https://www.macrumors.com/2020/06/25/apple-releases-safari-technology-preview-109/

**Pull request merged**
