### PR TITLE
Update footnote 5

### PR DESCRIPTION
**Pull request by DanielvandeVelde**
The bug on footnote 5 `background-attachment` has been closed: https://bugs.webkit.org/show_bug.cgi?id=219324, therefore all items with that footnote can be closed and are now acknowledged as supporting `background-attachment`

### CODE REVIEW

**Comment by DanielvandeVelde** [comment]
Updated the PR to make sure pipelines doesn't fail a second time.

**Review by rebtail — CHANGES_REQUESTED** [review]
Change

**Comment by Fyrd** [comment]
@DanielvandeVelde I just [tried this](https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment) on iOS 16.1 and the bug still seems to occur. Have you tested it yourself with other conclusions?

**Comment by Fyrd** [comment]
Closing based on my own testing.

**Pull request closed without merging**
