### PR TITLE
Updating the support on mobile browsers.

### PR DESCRIPTION
**Pull request by photopea**

### CODE REVIEW

**Comment by photopea** [comment]
Does anybody knwo what is going on? Editing JSON files is not enough?

**Comment by Schweinepriester** [comment]
<https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#unsupported-changes>:

> Currently it is not possible to:
>
> - Add a new browser or browser version

**Comment by photopea** [comment]
So these JSON files are generated automatically by some system? I thought you create them manually. 

So can you somehow process the fact, that latest mobile browsers support WebGL 2.0?

**Comment by Schweinepriester** [comment]
@Fyrd owns all this, so he'll probably answer those questions and consider the information :)

**Comment by Fyrd** [comment]
Have updated manually. Hope to update the latest Android chromium webview soon.

**Pull request closed without merging**
