### PR TITLE
Added Chrome for Android and Opera support.

### PR DESCRIPTION
**Pull request by daytonlowell**

### CODE REVIEW

**Comment by Fyrd** [comment]
Just tested in Chrome for Android & Opera for Android and does not appear to work as expected. What's your source/testcase?

**Comment by daytonlowell** [comment]
https://www.chromestatus.com/feature/6225984592281600

**Comment by Fyrd** [comment]
Ah right, it's supported behind a flag. So please change the values to `n d` like Chrome has it.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
