### PR TITLE
Overflow hidden bug

### PR DESCRIPTION
**Pull request by StepFlow**
https://github.com/w3c/csswg-drafts/issues/865

### CODE REVIEW

**Comment by Fyrd** [comment]
I think this should be rephrased: "One of the all of nearest element ancestor"...not clear to me what that means.

**Comment by jonjohnjohnson** [comment]
How about this?

"Any ancestor between the sticky element and it's user scrollable container with overflow computed as anything but visible/clip will effectively prevent sticking behavior."

And this would consolidate this third description with the second about safari and auto overflow.

**Comment by Fyrd** [comment]
Is that actually a browser bug or just spec-defined behavior? If the latter it should be listed under Notes instead. If it's the former it should mention which browsers are affected.

**Comment by jonjohnjohnson** [comment]
It's the latter. This clarification should be listed under Notes.

**Comment by Fyrd** [comment]
Has been added under Notes, so closing this PR.

**Comment by jonjohnjohnson** [comment]
@Fyrd I see you added my suggestion in the non-numbered notes, but I'd also suggest removing the second bug from the bugs list.

> A parent with overflow set to auto will prevent position: sticky from working in Safari
https://github.com/Fyrd/caniuse/blob/master/features-json/css-sticky.json#L37

First, it's not a bug as far as the spec is concerned. And two, the addition of the note encompasses what that "bug" was trying to communicate.

**Pull request closed without merging**
