### PR TITLE
Add MPEG-DASH

### PR DESCRIPTION
**Pull request by MekliCZ**

### CODE REVIEW

**Comment by MekliCZ** [comment]
Fixes #1278 :)

**Comment by Fyrd** [comment]
Thanks!

**Comment by Fyrd** [comment]
@MekliCZ This information doesn't seem to be correct... for example I'm able to play videos using http://dash-mse-test.appspot.com/dash-player.html in multiple browsers you say don't have support. Also 
https://bugs.chromium.org/p/chromium/issues/detail?id=109652 states support has existed in Chrome since at least version 37.

**Comment by MekliCZ** [comment]
The example you sent is using Media Source Extensions, it's not about native DASH support. You can use Shaka Player or Dash.js, but the browser doesn't support DASH natively. The same is Chromium bug, they are pointing to demo you sent, which is using MSE.

**Comment by Fyrd** [comment]
@MekliCZ Ah, got it, thank you. Yeah the whole thing's kind of confusing and it's hard to find a demo out there that relies only on native DASH support.

**Comment by MekliCZ** [comment]
@Fyrd Totally agree. It should be possible to check if browser supports DASH natively just by putting DASH stream to HTML5 video as a source. Or you could use JavaScript: ```video.canPlayType('application/dash+xml')```

**Comment by Fyrd** [comment]
@MekliCZ Thanks! That helps a lot. Feature's available on the site now. :)

**Pull request merged**
