### PR TITLE
Update loading attribute status

### PR DESCRIPTION
**Pull request by hangy**
The linked PR has been closed and has been integrated into the living standard.

### CODE REVIEW

**Comment by mkurz** [comment]
Can you also mark Firefox 75 as supported? The according issue was just marked as resolved: https://bugzilla.mozilla.org/show_bug.cgi?id=1542784

**Comment by hangy** [comment]
> Can you also mark Firefox 75 as supported? The according issue was just marked as resolved: https://bugzilla.mozilla.org/show_bug.cgi?id=1542784

Done. Thanks for the information! 🙂

**Comment by hangy** [comment]
> > Can you also mark Firefox 75 as supported? The according issue was just marked as resolved: https://bugzilla.mozilla.org/show_bug.cgi?id=1542784
> 
> Done. Thanks for the information! 🙂

Actually, I had to revert this, because we apparently can't add FF 75 features,  yet.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
