### PR TITLE
Add FIDO U2F API feature

### LINKED ISSUE #1718: Support FIDO U2F JavaScript API
Spec: https://fidoalliance.org/specs/fido-u2f-v1.0-nfc-bt-amendment-20150514/fido-u2f-javascript-api.html
Currently, only Google Chrome supports it. Mozilla is [working on it](https://bugzilla.mozilla.org/show_bug.cgi?id=1065729).

### PR DESCRIPTION
**Pull request by moreati**
Fixes #1718.

Currently only Chrome desktop 41+ supports U2F so the following warnings occur

```
$ nodejs validator/validate-jsons.js
[CK.json] WARNING: Expected total usage to be > 80, was 41.059624
[alt-an.json] WARNING: Expected total usage to be > 80, was 74.48
```

### CODE REVIEW

**Comment by Fyrd** [comment]
Interesting, never heard of this one. Thanks!

And don't worry about the warnings, those relate to usage data for any feature and are only occurring due to some statcounter anomolies.

**Comment by Fyrd** [comment]
@moreati Would you happen to know how to test support for this? Looking at the spec there should be some `u2f` object but I'm not seeing window.u2f or navigator.u2f in Chrome.

**Comment by moreati** [comment]
@Fyrd You must be on an https site, U2F requires a secure channel. For instance here on https://github.com

```javascript
> window.u2f
Object {
    EXTENSION_ID: "kmendfapggjehodndflmmgagdbamhnfd",
    EXTENSION_TIMEOUT_SEC: 30,
    ErrorCodes: Object,
    MessageTypes: ObjectWrappedChromeRuntimePort_: (t){this.port_=t},
    callbackMap_: ObjectgetMessagePort: (t){var e=chrome.runtime.connect(u2f.EXTENSION_ID,{includeTlsChannelId:!0});setTimeout(function(){t(new u2f.WrappedChromeRuntimePort_(e))},0)},
    getPortSingleton_: (t){u2f.port_?t(u2f.port_):(0==u2f.waitingForPort_.length&&u2f.getMessagePort(function(t){for(u2f.port_=t,u2f.port_.addEventListener("message",u2f.responseHandler_);u2f.waitingForPort_.length;)u2f.waitingForPort_.shift()(u2f.port_)}),u2f.waitingForPort_.push(t))},
    port_: null,
    register: (t,e,n,r){u2f.getPortSingleton_(function(i){var s=++u2f.reqCounter_;u2f.callbackMap_[s]=n;var o={type:u2f.MessageTypes.U2F_REGISTER_REQUEST,signRequests:e,registerRequests:t,timeoutSeconds:"undefined"!=typeof r?r:u2f.EXTENSION_TIMEOUT_SEC,requestId:s};i.postMessage(o)})},
    reqCounter_: 0,
    responseHandler_: (t){var e=t.data,n=e.requestId;if(!n||!u2f.callbackMap_[n])return void console.error("Unknown or missing requestId in response.");var r=u2f.callbackMap_[n];delete u2f.callbackMap_[n],r(e.responseData)},
    sign: (t,e,n){u2f.getPortSingleton_(function(r){var i=++u2f.reqCounter_;u2f.callbackMap_[i]=e;var s={type:u2f.MessageTypes.U2F_SIGN_REQUEST,signRequests:t,timeoutSeconds:"undefined"!=typeof n?n:u2f.EXTENSION_TIMEOUT_SEC,requestId:i};r.postMessage(s)})},
    waitingForPort_: Array[0],
    __proto__: Object,
}
```
but on http://example.com
```javascript
> window.u2f
undefined
```
Would you like me to add a note to that effect?

**Comment by Fyrd** [comment]
Oh weird, I try that on https://google.com and it's undefined. Weird. Good enough though, thanks!

**Comment by moreati** [comment]
You're right, I'd forgotten about [u2f-api.js](https://github.com/google/u2f-ref-code/blob/no-extension/u2f-gae-demo/war/js/u2f-api.js). Apparently Github is ahead of the curve, and includes it in their pages.

I'll try find a semi decent introduction to the U2F Javascript API and add it as a link.

**Pull request merged**
