### PR TITLE
Safari 9 word-break: keep-all Support

### PR DESCRIPTION
**Pull request by kiding**
Safari 9 and iOS Safari 9 ([bug 123782](https://bugs.webkit.org/show_bug.cgi?id=123782)) started supporting word-break: keep-all, making it fully supported by all major browsers.

### CODE REVIEW

**Comment by Fyrd** [comment]
Doesn't seem to work in my test...do you have a demo that shows it working?

**Comment by kiding** [comment]
screen shot 2015-12-24 at 10 01 26 am

I believe it's one of the properties intended only for CJK(Chinese-Japanese-Korean.) You can check out [the example on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break).

**Comment by yisibl** [comment]
Yes! Safari supported!

**Comment by Fyrd** [comment]
Alright, thanks! Can confirm now, guess I need to update my test.

**Comment by yisibl** [comment]
@Fyrd Thanks!

**Pull request merged**
