### PR TITLE
Canvas .toDataUrl() fixing #1564

### PR DESCRIPTION
**Pull request by pkuczynski**

### CODE REVIEW

**Comment by Fyrd** [comment]
As this seems to be widely supported, almost matching support for `canvas` itself, I'd suggest just including support there and adding some notes. I'll use your info and take care of that. Thanks!

**Comment by pkuczynski** [comment]
Well, I tend to disagree, especially when it comes to mobile. I wanted to help you and worked on a ticket from the Issues list. Feel a bit like I wasted the time. How shall we proceed in the future to avoid that?

**Comment by Fyrd** [comment]
@pkuczynski Why is it wasted time if I included most of the information anyway? Besides it seems your information wasn't all entirely accurate, you had old Opera Mobile and UC browser with no support though they seem to support it just fine. In the future if you don't know and are unable to test, just set the value to `u` for unknown.

For future issues if it seems it may already be part of another feature I'd suggest just checking with me first, otherwise it should be fine. As I don't have the time to look into every single suggestion in advance there may be the occasional one that doesn't make sense to add.

**Comment by pkuczynski** [comment]
Fair enough :)

Most of my commits is based on the Google research, not actual testing. In the future if I won't be able to find any valuable information I will fill it up with "u".

**Pull request closed without merging**
