### PR TITLE
Add CSS Environment Variables env()

### PR DESCRIPTION
**Pull request by ausi**
See #3787.

`env()` is supported since Safari 11, Chrome 69, Opera 56.

### CODE REVIEW

**Comment by Malvoz** [comment]
Want to add MS Edge feature suggestion to that?
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/34589707-css-environment-variables

Should probably extend keywords to "CSS variables" here aswell.

**Comment by ausi** [comment]
@Malvoz done.

**Comment by Malvoz** [comment]
Thanks, I have further requests on that though - if a user searches explicitly for e.g. "css env()" or "css variables" this would not show with the current keywords:

`env,safe-area-inset,constant,variables`.

Can I bother you with an updated list on that?

`css env(),constant(),css variables,safe-area-inset-top,safe-area-inset-right,safe-area-inset-bottom,safe-area-left`

**Comment by ausi** [comment]
@Malvoz done.

**Comment by Fyrd** [comment]
Thanks!

**Comment by kiding** [comment]
https://github.com/Fyrd/caniuse/blob/12e8cedf52b3caf5adcfa7ccac31357484c5634d/features-json/css-env-function.json#L348 
I believe `shown` should be true unless there is any particular reason.

**Pull request merged**
