### PR TITLE
minlength (and tooshort) are supported by Edge 17

### PR DESCRIPTION
**Pull request by dstorey**

### CODE REVIEW

**Comment by mkurz** [comment]
@dstorey Was note 4 mentioned here fixed as well: https://caniuse.com/#feat=maxlength ?
(also see https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4678527/)

**Comment by Fyrd** [comment]
Thanks!

**Comment by mkurz** [comment]
Hey @dstorey - did you find time to check [my comment above](https://github.com/Fyrd/caniuse/pull/3997#issuecomment-357310424)? Thanks!

**Comment by mkurz** [comment]
Pinging @dstorey

**Comment by mkurz** [comment]
@dstorey https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4678527/ was not fixed with Edge 17!
Check out this test case: http://output.jsbin.com/xutife/1
(taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1203844)

**Pull request merged**
