### PR TITLE
Update opus.json

### PR DESCRIPTION
**Pull request by mattbrundage**
Fix typo; proper casing

### CODE REVIEW

**Comment by Fyrd** [comment]
The intent in those notes is to say "Support refers to use **[of this format]** using the `audio` element, not other conditions" so removing the word "use" doesn't make sense. I'm open for other suggestions to rephrase that though.

**Comment by mattbrundage** [comment]
The implied prepositional phrase "of this format" was not apparent to me. And the word "use" followed directly by "using" is awkward, especially when "use" can be construed as a verb.

A suggestion: "Support refers to this format's use in the ``audio`` element, not other conditions.

**Comment by Fyrd** [comment]
@mattbrundage Good suggestion, let's go with that. Thanks!

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
