### PR TITLE
Add srcset bug in Edge 14 (issue #3262)

### PR DESCRIPTION
**Pull request by OliverO2**
See #3262.

### CODE REVIEW

**Comment by Fyrd** [comment]
Support should be "partial" here at worst, which uses `a` instead of `n`. Also according to the bug report it occurs in Edge 13 as well.

**Comment by OliverO2** [comment]
@Fyrd Thanks for the review. I've included Edge 13.

I would agree with "partial" support if the feature was at least useful under _any_ known circumstance or with some known workaround. Since Edge 13 and 14 cannot reliably display images _at all_ when `srcset` is present, what would be the meaning of "partial" in this case?

**Comment by Fyrd** [comment]
I don't really have much experience with this issue, but I'll accept your changes for now since you're right that if it's not reliable at all it's effectively unusable. May revisit this in the future if others disagree.

**Comment by OliverO2** [comment]
Agreed. We had a site which seemed to work reliably with Edge 14 and srcset and for some time. When we just changed the timing of asynchronous script and font loading, rendering of images broke on Edge 14 about 25% of the time, though the srcset stuff remained identical.

If someone came up with information to reproducibly correct the situation, it would be most welcome.

**Pull request merged**
