### PR TITLE
Add Edge support for AVIF

### PR DESCRIPTION
**Pull request by captainbrosset**
Edge 121 will have support for AVIF.

### CODE REVIEW

**Comment by tats-u** [comment]
Edge 121 is still Beta. MSFT could disable AVIF in stable again.

**Comment by Schweinepriester** [comment]
@captainbrosset appears to work for Microsoft, so I'm strongly assuming he knows for sure. Also backed up by that MDN has merged the MR already and https://github.com/web-platform-dx/web-features/pull/515 is even opened by someone else notable.

Yet, I was wondering if there is some public information/commitment from Microsoft out there…?

**Comment by tats-u** [comment]
@Schweinepriester 

> @ captainbrosset appears to work for Microsoft, so I'm strongly assuming he knows for sure. Also backed up by that MDN has merged the MR already and https://github.com/web-platform-dx/web-features/pull/515 is even opened by someone else notable.

Looks like we can celebrate that good news.

> Yet, I was wondering if there is some public information/commitment from Microsoft out there…?

I hope there is one.

**Comment by ADNewsom09** [comment]
just for further reference several news outlets are reporting that AV1 and AVIF are supported starting in 121. they are citing this edge dev's post: https://mas.to/@patrickbrosset/111606269190204459 as their source.

**Review by ADNewsom09 — APPROVED** [review]
I have confirmed this is accurate in my testing.

**Comment by captainbrosset** [comment]
> @captainbrosset appears to work for Microsoft, so I'm strongly assuming he knows for sure. Also backed up by that MDN has merged the MR already and [web-platform-dx/web-features#515](https://github.com/web-platform-dx/web-features/pull/515) is even opened by someone else notable.

I do work for Microsoft, and on Microsoft Edge.

> Yet, I was wondering if there is some public information/commitment from Microsoft out there…?

Not yet. As soon as 121 gets released, the release notes will appear here: learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel. This should hopefully happen tomorrow, unless there's some delay introduced in the release notes publishing process (which can always happen).

**Comment by Fyrd** [comment]
Added Edge 121 and set support for AVIF for it. Thanks!

**Pull request closed without merging**
