### PR TITLE
CSS3 font-kerning (#946)

### PR DESCRIPTION
**Pull request by pkuczynski**

### CODE REVIEW

**Comment by Fyrd** [comment]
Currently for Chrome you have `x` as a value, this needs to be either `a x` or `y x` for the data to be valid. Can you update your PR with that change? Thanks.

**Comment by pkuczynski** [comment]
Fixed. You can merge in now :)

**Comment by Fyrd** [comment]
@pkuczynski Looks like there's still a problem (you can tell from the "The Travis CI build failed" message). Looking at the [details](https://travis-ci.org/Fyrd/caniuse/builds/58409541) I see Firefox is missing support values, `d #1` should be `n d #1`

**Comment by Fyrd** [comment]
@pkuczynski Can you fix? ^

**Comment by pkuczynski** [comment]
Hi @Fyrd, sorry for delay. I am currently travelling abroad, but will try to look into this in next 24hrs...

**Comment by Fyrd** [comment]
@pkuczynski Ah, no rush, just thought I'd remind you. :)

**Comment by pkuczynski** [comment]
Fixed :)

**Pull request merged**
