### PR TITLE
Microsoft Edge 74 supports :focus-within

### PR DESCRIPTION
**Pull request by samrueby**
The new Microsoft Edge, which is now in beta, supports :focus-within.

### CODE REVIEW

**Comment by samrueby** [comment]
I don't understand why the checks failed.

**Comment by HM100** [comment]
> I don't understand why the checks failed.

Because adding new browser versions via PR isn't allowed.

**Comment by Schweinepriester** [comment]
As #4861 has been completed, I believe this PR can be closed, as the desired listing is present: <https://caniuse.com/#feat=css-focus-within>

image

**Comment by samrueby** [comment]
Thank you

**Pull request closed without merging**
