### PR TITLE
Rename Native File System to File System Access

### PR DESCRIPTION
**Pull request by tomayac**
For context: https://bugs.chromium.org/p/chromium/issues/detail?id=1110509#c2.

### CODE REVIEW

**Comment by Schweinepriester** [comment]
The changed URLs give context as well, but <https://bugs.chromium.org/p/chromium/issues/detail?id=1110509#c2> leads to `Permission denied.` for me, logged in as well as anonymous.

**Comment by tomayac** [comment]
Sorry, this bug is apparently internal-only. The spec commit where the renaming happened is the better context anyway: https://github.com/WICG/file-system-access/commit/58d2fe8453c9b1ff9bdabadd3dde0f0757cfddd7.

**Comment by Fyrd** [comment]
@tomayac Mind resolving the conflicts so I can merge? Thanks!

**Comment by tomayac** [comment]
> Mind resolving the conflicts so I can merge? Thanks!

Thanks for looking into this! The "Resolve conflicts" button is disabled for me, and, following the [command line instructions](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line), I don't see a conflict locally either (and could cleanly merge my change into the `master` branch of my fork). Not sure what's happening. The change is a straightforward file rename and some in-file renames. Anything else I could do?

**Comment by Fyrd** [comment]
Ah, I only just noticed this PR changes the file name as well. In general I'd like to keep that the same (to prevent broken links etc). Could you change the PR to only affect the original file's data? If it's too much trouble I can also just make the changes manually.

**Comment by tomayac** [comment]
Restored the previous file name, which caused the conflict to go away. Weird. Anyway, this should hopefully be ready to merge then.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
