### PR TITLE
remove edge uservoice links

### PR DESCRIPTION
**Pull request by yukulele**

### CODE REVIEW

**Comment by yukulele** [comment]
Oh, I had not noticed #5892, sorry...

Indeed I'm not sure it's relevant to keep links to disappeared pages that concern a no longer developed browser.

**Comment by Schweinepriester** [comment]
> Indeed I'm not sure it's relevant to keep links to disappeared pages that concern a no longer developed browser.

Yeah, no, we agreed on removing them but keeping the archive links in the history :)
(But I still have to finalize that, I'll try to do it later today.)

**Comment by Schweinepriester** [comment]
Aaand #5892 is finally ready 😅

**Comment by Fyrd** [comment]
Closing as completed by #5892 . Thanks both!

**Pull request closed without merging**
