### PR TITLE
Safari TP 114: MediaRecorder & WebGL 2.0 by default

### PR DESCRIPTION
**Pull request by Schweinepriester**
<https://webkit.org/blog/11300/release-notes-for-safari-technology-preview-114/>

> Enabled MediaRecorder by default on macOS ([r267225](https://trac.webkit.org/changeset/267225/webkit/))

> Enabled WebGL2 by default ([r267027](https://trac.webkit.org/changeset/267027/webkit/))

### CODE REVIEW

**Comment by mkurz** [comment]
@Schweinepriester Can you run Safari TP 114 on your machine?

**Comment by Schweinepriester** [comment]
@mkurz Yes! Ask away :)

**Comment by mkurz** [comment]
@Schweinepriester Great!
Can you check if TP 114 does show UI date pickers for input `type="datetime-local"` and/or `type="date"`? Also `type="time"`, `type="month"` and `type="week"` would be interesting.
To make things easy I prepared a demo here: https://jsfiddle.net/8gw2yk5e/

I am pretty sure part of those inputs should now show a UI because [Bug 214946](https://bugs.webkit.org/show_bug.cgi?id=214946) was marked as fixed in September. Also the TP 114 [release notes](https://webkit.org/blog/11300/release-notes-for-safari-technology-preview-114/) contains a section about "Date and Time Inputs".

Maybe you can post a screenshot of those pickers if they are shown?
Also the caniuse data for https://caniuse.com/input-datetime would need an update.

Thanks!

**Comment by Schweinepriester** [comment]
@mkurz wondered about those as well when reading the release notes :) 

I'm afraid there is currently no UI:

Bildschirmfoto 2020-10-10 um 19 37 30

I've tried interacting and entering random stuff as well, behaves like `type="text"`...

I'm on macOS 10.15.7 Catalina, maybe it's only available on 11.0 Big Sur as are other features, but I think that's unlikely in this case.

**Comment by mkurz** [comment]
@Schweinepriester This is strange. [Bug 214946](https://bugs.webkit.org/show_bug.cgi?id=214946) (which even has a [screenshot attached](https://bug-214946-attachments.webkit.org/attachment.cgi?id=405589)) was marked as fixed and also the corresponding changeset [266063](https://trac.webkit.org/changeset/266063/webkit) should have made it into the TP.
If you look at the [release notes](https://webkit.org/blog/11300/release-notes-for-safari-technology-preview-114/) it says
image
Looking at [those list of commits](https://trac.webkit.org/log/webkit/?stop_rev=265893&rev=267325&limit=1432) it also contains the above changeset
image
Maybe they disabled it before shipping or you are right and it's available in Big Sur only...

**Comment by Fyrd** [comment]
Thanks! Merging the changes, though feel free to continue the discussion ;)

**Comment by mkurz** [comment]
@Schweinepriester Safari TP 115 [got released](https://webkit.org/blog/11333/release-notes-for-safari-technology-preview-115/). Can you please re-check if the date input types have a UI now? Thanks!

**Comment by mkurz** [comment]
@Schweinepriester Seems like the date picker UI is shipped now, according to this comment: https://bugs.webkit.org/show_bug.cgi?id=214946#c27 (comment 27)
Can you confirm?

**Comment by Schweinepriester** [comment]
@mkurz I can confirm! 🎉

Bildschirmfoto 2020-10-23 um 11 46 00

Bildschirmfoto 2020-10-23 um 11 46 33

Will you do the honors (create the PR)?

**Comment by mkurz** [comment]
> I can confirm! :tada:

Great! So does it show actual date/time pickers popups to choose the date/time?

> Will you do the honors (create the PR)?

You can do that if you have time, I am very busy and short on time even for small tasks.

**Comment by mkurz** [comment]
@Schweinepriester see #5669

**Pull request merged**
