### PR TITLE
Update browser data for display:contents bug

### PR DESCRIPTION
**Pull request by hidde**
The severe `display:contents` bug was fixed in Chrome 89, see also [Good news about display: contents and Chrome](https://rachelandrew.co.uk/archives/2021/03/11/good-news-about-display-contents-and-chrome/)

This is my first contribution, hope this is the correct way. 

I have verified it in Chrome 89, and also updated the data from 90-92, assuming it will still be fixed in those releases.

### CODE REVIEW

**Comment by Schweinepriester** [comment]
Looking good!

How have you verified it? Do you have a testcase? Maybe are even able to share it?
I'm asking because then we (you) could check Edge 89 as well... :)

**Comment by hidde** [comment]
I used 

- for tables https://codepen.io/aardrian/pen/xxGEKKJ
- for lists https://codepen.io/aardrian/pen/abOBWKa and https://codepen.io/rachelandrew/pen/oNYapVb
- for headings https://codepen.io/aardrian/pen/WNvoOpM
- for buttons https://codepen.io/aardrian/pen/NWqbggX

**Comment by hidde** [comment]
Have just verified they also work in Edge 89, will update the PR.

**Comment by hidde** [comment]
Have just updated, thanks for the nudge!

**Review by Schweinepriester — APPROVED** [review]

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
