### PR TITLE
IE11 fires an input event when an input with placeholder is focused

### PR DESCRIPTION
**Pull request by arleytriana**

### CODE REVIEW

**Comment by Fyrd** [comment]
I'd suggest putting this under "bugs" instead. Numbered notes is more for explaining missing/partial support. In fact, you can probably just copy the second bug on the [placeholder](https://github.com/Fyrd/caniuse/blob/master/features-json/input-placeholder.json) entry which lists the same thing.

**Comment by cvrebert** [comment]
>  In fact, you can probably just copy the second bug on the placeholder entry which lists the same thing.

Why list the same bug twice? Even the link is the same.

**Comment by Fyrd** [comment]
@cvrebert This one would be for the "input" event, the other for the placeholder one. The bug applies to both, so it would be useful to include it in both places.

**Comment by cvrebert** [comment]
Ah. Derp.

**Comment by Fyrd** [comment]
Went ahead and implemented my suggestion manually, so closing.

**Pull request closed without merging**
