### PR TITLE
Fix speech-synthesis.json: Firefox for Android already supports this in v62

### PR DESCRIPTION
**Pull request by EbiEbiEvidence**
Here it is: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/62#APIs

### CODE REVIEW

**Comment by Fyrd** [comment]
Can confirm support in Firefox for Android, but does not appear to work in the Android WebView.

**Comment by EbiEbiEvidence** [comment]
@Fyrd That's right! I was wrong! I fixed it

**Comment by EbiEbiEvidence** [comment]
Moreover, i cant find that opera supports it.
Opera only supports Speech Synthesis.
More at: https://blogs.opera.com/desktop/changelog-27/

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
