### PR TITLE
preconnect stopped working in Firefox 71

### PR DESCRIPTION
**Pull request by da2x**
I've tested every version from 70 to 82. 70 is the last version where `<link rel=preconnect` worked in Firefox. Firefox 71+ issues no DNS requests and doesn't try to establish a TCP or TLS session to preconnect origins. (I'm aware of the difficulties in testing this properly with DNS caching and stuff. This was verified with WireShark.)

### CODE REVIEW

**Comment by Schweinepriester** [comment]
Could be <https://bugzilla.mozilla.org/show_bug.cgi?id=1543990>?

**Comment by da2x** [comment]
68, and 69 (plus 70) work. I can't currently test older versions.

**Comment by Fyrd** [comment]
Don't have an easy way of confirming this but it does seem https://bugzilla.mozilla.org/show_bug.cgi?id=1543990 confirms it, so merging for now. Thanks!

**Comment by da2x** [comment]
It stopped working in 66, but it worked in 65, 67, 68, 69, and 70; before it stopped working again in 71 onwards. Bug 1543990 is probably just as good of a tracking bug as any other.

**Pull request merged**
