### PR TITLE
Spartan has partial srcset support

### PR DESCRIPTION
**Pull request by zcorpan**
https://twitter.com/gregwhitworth/status/582685630154440704

### CODE REVIEW

**Comment by Fyrd** [comment]
@dstorey I believe you set this to `y`, do you think it's safe to say `srcset` will have complete support on launch or should we go with partial support for now?

**Comment by dstorey** [comment]
@Fyrd  we’ve having some issues with srcset as the picturefill polyfill breaks, assuming supporting srcset means supporting picture too :/  https://github.com/scottjehl/picturefill/issues/478 Breaks major sites. So we're looking into what to do internally.  

We support srcset and currentSrc, but not sizes and picture, which I believe are separate items here? 

It looks like we have to regress out support and remove currentSrc due to Picturefill being broken https://github.com/scottjehl/picturefill/issues/478#issuecomment-90306153

If partial here means not supporting sizes and (now) currentSrc then we should set it to partial.

**Comment by zcorpan** [comment]
Partial here means not supporting w/sizes.

@dstorey you could mark currentSrc as `[Replaceable]` until you also support `HTMLPictureElement` to fix the picturefill issue I think.

**Comment by Fyrd** [comment]
Yeah, `sizes` is more srcset-related, `picture` is its own feature.

**Comment by zcorpan** [comment]
@gregwhitworth FYI (see my comment above about `[Replaceable]`)

**Comment by gregwhitworth** [comment]
@zcorpan We considered that option.

**Pull request merged**
