### PR TITLE
Safari TP 138

### PR DESCRIPTION
**Pull request by Schweinepriester**
Besides #6104 (pls merge!) there is more (to change on caniuse):
https://webkit.org/blog/12176/release-notes-for-safari-technology-preview-138/
> - Enabled the `resolution` media query by default ([r286874](https://trac.webkit.org/changeset/286874/webkit/))
> - Enabled the CSS Contain property by default ([r286828](https://trac.webkit.org/changeset/286828/webkit/))
> …
> - Unprefixed `-webkit-mask` ([r286795](https://trac.webkit.org/changeset/286795/webkit/))

## <https://tests.caniuse.com/css-containment>:

Same as before, now enabled by default 🎉 

## <https://tests.caniuse.com/css-media-resolution>:

Safari TP 138 now matches Chrome (unprefixed) as opposed to before. Couldn't find it in <https://wpt.fyi>…

Safari TP 138:

image

Chrome 97:

image

Safari 15.2:

image

## <https://tests.caniuse.com/css-masks>

Now works unprefixed as well, but note 1 probably remains - to go further more testing would be required. Maybe https://wpt.fyi/results/css/css-masking/mask-image?label=master&label=experimental&aligned&q=css%20mask will change once at TP 138…

Safari TP 138:

image

Chrome 97:

image

Safari 15.2:

image

### CODE REVIEW

**Comment by Fyrd** [comment]
Almost missed this one. :) Thanks!

**Comment by Schweinepriester** [comment]
Thanks! Don't miss #6104 0:-) 0:-) 0:-)

**Comment by mkurz** [comment]
@Schweinepriester Just to let you know Safari 15.3 was released, not sure if you want to have a look if something need to be changed regarding caniuse.com

**Comment by Schweinepriester** [comment]
@mkurz Thanks, maybe! I was looking for the changelog, but didn't find anything yet - did you?

I only found https://support.apple.com/en-us/HT213058 so far regarding 15.3?
I would assume Safari 15.3 is much as [iOS 15.3 more or less containing only fixes](https://support.apple.com/en-us/HT212788#153)…

Doesn't even have an entry on https://developer.apple.com/documentation/safari-release-notes (yet).

However, there's a juicy 15.4 beta there! 🤯🤩
=> https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes

… I'll create an issue, thanks, will give creds, lets move there! :)

**Comment by mkurz** [comment]
@Schweinepriester I think it's just security fixes as well.

**Pull request merged**
