### PR TITLE
Web Application Manifest landed in Firefox 58

### PR DESCRIPTION
**Pull request by tomByrer**
https://platform-status.mozilla.org/#app-manifest
I can't find the 'In development note to delete.

cheers & thanks for your resource!

### CODE REVIEW

**Comment by Fyrd** [comment]
It's supported in Firefox for Android, not Firefox for Desktop I believe. If you can find evidence to the contrary let me know!

**Comment by tomByrer** [comment]
TY for the info.  I'm assuming the MDN footer is outdated, which is why I went with platform-status.mozilla.org  

Is there a site that gives a quick test?

**Comment by Fyrd** [comment]
I have a test here that just checks if the manifest was downloaded by the browser when adding the page to the homepage:
https://tests.caniuse.com/web-manifest.php

**Comment by Malvoz** [comment]
I didn't realize there was a PR on this...

It is correct, FireFox implemented this - for Android only, so this should be "_partial support_". 
@tomByrer if you agree with changes in https://github.com/Fyrd/caniuse/pull/4629, do you want to close this?

**Comment by Fyrd** [comment]
Closing until further info comes to light.

**Pull request closed without merging**
