### PR TITLE
Add Sponsor badge to the GitHub Repo

### PR DESCRIPTION
**Pull request by coliff**
Add Sponsor badge to the GitHub Repo with link to https://www.patreon.com/join/caniuse

REF: https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

### CODE REVIEW

**Comment by Fyrd** [comment]
❤️ Thanks!

**Comment by coliff** [comment]
cool - you just need to turn it on in the settings now:
https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

**Comment by Fyrd** [comment]
Done, thanks again!

**Comment by sunlight708** [comment]
Facebook authentication coad

**Pull request merged**
