### PR TITLE
Update DOMMatrix support

### PR DESCRIPTION
**Pull request by dstorey**
No browser currently support DOMMatrix for SVG, which is half of the reason for it to exist (merge CSSMatrix and SVGMatrix)

### CODE REVIEW

**Comment by Fyrd** [comment]
@dstorey Can you provide or point me to a test for DOMMatrix support for SVG? Looked around a bit and wasn't able to find anything.

**Comment by dstorey** [comment]
Currently https://github.com/w3c/web-platform-tests/pull/10296 but it isn't merged yet

**Comment by dstorey** [comment]
(or you can just look at the browser WebIDL files and see that the define SVGMatix, SVGPoint, et al)

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
