### PR TITLE
Add feature: Generic Sensor-based motion sensors

### LINKED ISSUE #2776: Magnetometer support
https://w3c.github.io/magnetometer/

### LINKED ISSUE #2777: Gyroscope sensor
https://w3c.github.io/gyroscope/

### LINKED ISSUE #2778: Accelerometer sensor
https://w3c.github.io/accelerometer/

### PR DESCRIPTION
**Pull request by anssiko**
- Add Accelerometer
- Add Gyroscope
- Add Magnetometer
- Add Orientation Sensor

Fix #2778
Fix #2777
Fix #2776

### CODE REVIEW

**Comment by anssiko** [comment]
@Fyrd, I'm a bit puzzled by this error:

```
Error: [accelerometer:and_chr:64] Browser version missing: and_chr 64
```
If I add a key for 64 `node validator/validate-jsons.js` reports:

```
Error: [accelerometer:and_chr] Extra key found in and_chr: "67"
```

Something obvious I've overlooked?

I see other features use a similar structure, i.e. only define one key for `and_chr`.

**Comment by cvrebert** [comment]
> Something obvious I've overlooked?

Adding new browser versions via JSON isn't supported:
https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#unsupported-changes
As far as caniuse JSON is concerned, Android Chrome's only possible version is currently 64.
Fyrd doesn't track historical compatibility data for mobile browsers for...some reason.

**Comment by Fyrd** [comment]
@cvrebert is correct. As for the reason, see #3518. I am in the process of finding a solution for that, though.

**Comment by anssiko** [comment]
@Fyrd, thanks for explaining the rationale, and thanks @cvrebert for pointing out the fix.

I pushed a fix that includes `and_chr` version 64 data only and this PR now passes Travis CI.

@Fyrd, feel free to merge if the PR looks good otherwise.

**Comment by anssiko** [comment]
@fyrd, I notice this PR was merged (thanks!), and the site content was updated in the following data update: https://github.com/Fyrd/caniuse/commit/4fa442c7b3203eaa8e7687063855a6e909aa70b0

In this data update the following files were added:
```
features-json/orientation-sensor.json
features-json/accelerometer.json
features-json/gyroscope.json
features-json/magnetometer.json
```

I noticed `orientation-sensor` is already `"shown":true`:

https://caniuse.com/#feat=orientation-sensor

Here is further data that should help you flip the `shown` flag to `true` also for `accelerometer`, `gyroscope` and `magnetometer` (per [your guidance](https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#adding-a-feature)):

Cross-browser test suites for all these features:
* https://github.com/w3c/web-platform-tests/tree/master/accelerometer
* https://github.com/w3c/web-platform-tests/tree/master/gyroscope
* https://github.com/w3c/web-platform-tests/tree/master/magnetometer

Respective test results on Chrome 67 for Android (CA) and Chrome 67 for Desktop (CD): 
* https://w3c.github.io/test-results/accelerometer/all.html
* https://w3c.github.io/test-results/gyroscope/all.html
* https://w3c.github.io/test-results/magnetometer/all.html

In addition, for manual testing we have developed a tool that complements the automated cross-browser test suite:
https://intel.github.io/generic-sensor-demos/sensor-tester/build/bundled/

Please let me know if you have any questions or if I can be of further help.

**Comment by Fyrd** [comment]
Hi @anssiko, thanks for all the links and information. I notice when I run those tests on either of my Mac laptops they mostly fail, is that expected (due to missing sensors in the device)? 

Also even on Chrome 67 for Android I notice a simple test of `'Magnetometer' in window` returns false. Am I missing something?

**Comment by anssiko** [comment]
@Fyrd, correct, your Mac does not have the supporting sensor hardware. Some (older!) models do.

Magnetometer is available by enabling the ”Generic Sensor Extra Classes” experimental flag in `about:flags` as noted. The rest of the sensors are enabled by default in Chrome 67.

**Comment by Fyrd** [comment]
Ah, that explains things, thanks. Should all upcoming versions of Chrome not also use `n d #1` for Magnetometer then? (I'll go ahead and fix that)

**Comment by Fyrd** [comment]
Okay, all features are now on the site. Thanks again!

**Pull request merged**
