### PR TITLE
Safari 17 supports JPEG XL

### PR DESCRIPTION
**Pull request by Schweinepriester**
Stopped reading the changelog as soon as I noticed:

https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes

> Added support for JPEG XL. (100641584)

To quote [this tweet](https://twitter.com/JpegXl/status/1665815159854489603)

> The irony will be strong when the first major browser to support the format that was developed by Google (and Cloudinary) will turn out to be... Safari!

🥳

~~I have no way of testing yet, so please, if you can, check <https://tests.caniuse.com/jpegxl>!~~

Thomas Steiner was so nice to test, via <https://mastodon.social/@tomayac@toot.cafe/110497493927324514>:

> Seems to work on both mobile and desktop.

image

### CODE REVIEW

**Comment by jensimmons** [comment]
Confirming that JPEG XL will be supported by Safari 17 on macOS Sonoma, macOS Ventura and macOS Monterey, as well as iOS, iPadOS, watchOS, and visionOS.

**Comment by Schweinepriester** [comment]
That is so great to hear! 🤩🚀

https://gfycat.com/confusedvengefulindianabat-nod-zach-galifianakis

**Comment by Fyrd** [comment]
Thanks, awesome!

**Comment by goodusername123** [comment]
Currently the beta version of Safari 17 does not support animation(s) and supposedly also doesn't support embedded color profiles, I am unsure when and if this will be resolved so maybe it's worth it to have a note about the support not being full somewhere.

**Comment by goodusername123** [comment]
@Schweinepriester Animation(s) can be seen not working at the bottom of the website located here: https://jpegxl.info/test-page/ . I do not currently have a testcase on hand for color profiles not working but if needed I could eventually provide/get a example for them.

**Pull request merged**
