### PR TITLE
html5semantic: Edge doesn't support <time> yet

### PR DESCRIPTION
**Pull request by cvrebert**
https://dev.modern.ie/platform/status/timeelement/

### CODE REVIEW

**Comment by dstorey** [comment]
Neither does Safari, Chrome or Opera http://jsfiddle.net/825wtfvf/ . Firefox does.

**Comment by cvrebert** [comment]
Perhaps `<time>` ought to be split out into a separate file then.

**Comment by Fyrd** [comment]
I've always kind of felt that it barely matters for developers whether a browser supports `<time>` or not. It's real value lies in what search engines and content scrapers can get from it, no? AFAICT the only difference in browser support is whether or not it's treated as an unknown element.

**Comment by dstorey** [comment]
I more or less agree. Same with <data>, which isn't listed but is of same ilk. (that has even less, as only has value attribute)

**Comment by Fyrd** [comment]
Just added this information as a known issue, thanks for the detailed info, @dstorey.

**Pull request closed without merging**
