### PR TITLE
text-size-adjust supported with prefix in Project Spartan

### PR DESCRIPTION
**Pull request by dstorey**
…at least according to the test.caniuse.com page.

### CODE REVIEW

**Comment by Fyrd** [comment]
Hmmm...technically this is supposed to be for mobile browsers only. Some desktop browsers (like Firefox) acknowledge the property but afaict don't actually do anything with it.

**Comment by dstorey** [comment]
Yeah, I didn't test too much to see how it handles it as wasn't sure when it suppose to kick in. Gathered it would be used for tablets et al on Windows 10 as we have a touch browser by default.

**Comment by Fyrd** [comment]
Would you happen to have access to a tablet with Windows 10 on it? If so, could you try out http://tests.caniuse.com/tsa.html and see if clicking the button affects the font size?

**Comment by dstorey** [comment]
I have a touch screen laptop at the office, Will run in tomorrow AM and let you know

**Comment by dstorey** [comment]
Looks like it isn’t working on desktop, at least with a touch screen laptop, so this can be closed won't fix.

**Comment by Fyrd** [comment]
Cool, thanks for checking.

**Pull request closed without merging**
