### PR TITLE
Update Firefox support note

### PR DESCRIPTION
**Pull request by sroucheray**
`::cue` pseudo-element is supported in Firefox, I tested it in FF 100 on Linux. This is also what is noted in the last comment of the bug https://bugzilla.mozilla.org/show_bug.cgi?id=865395#c21

### CODE REVIEW

**Comment by Schweinepriester** [comment]
The notes are looking good, thank you!
Do you want to change the entries for 55+ (`#1` => `#2`)?

**Comment by sroucheray** [comment]
Sorry I am not sure I understand. The note 55+ is numbered #2 already, in the second commit. Do you want me to change that?

**Comment by Fyrd** [comment]
@sroucheray In addition to mentioning "Firefox 55+" in note 2, you'll also want to update the "stats" entries to refer to that note, so `"55": "y #2"`, etc.

**Review by Schweinepriester — APPROVED** [review]

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
