### PR TITLE
Add new feature: CSS touch-action level 2 values

### PR DESCRIPTION
**Pull request by lpd-au**
As part of their work on Pointer Events Level 2, the Pointer Events Working Group have added five new property values to touch-action:

* `pan-up`, `pan-down`, `pan-left`, `pan-right`: https://github.com/w3c/pointerevents/issues/6
* `pinch-zoom`: https://github.com/w3c/pointerevents/issues/29

Currently only Chrome 56+ provides full support for these additions. Rather than retrospectively change most browser versions from complete to partial support for touch-action, this patch creates a new child feature for touch-action level 2. It also removes references of pinch-zoom being non-standard.

PEWG's pan tests can be found here: http://w3c-test.org/pointerevents/
Blink's pinch-zoom tests can be found here: https://codereview.chromium.org/2126323002/

I tested manually using the web inspector in Firefox 52 and Opera 42. Chrome and Edge support values are taken from their status pages. [MDN's browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action#Browser_compatibility) is also mostly complete.

Some sample stuff: [carousel](http://dtapuska.github.io/touch-action/carousel.html), [pull to refresh](http://output.jsbin.com/dahaga).

The one bug references this issue: https://github.com/w3c/pointerevents/issues/166

### CODE REVIEW

**Comment by Fyrd** [comment]
Nice, thanks! Can you replace the `p` values with `a`? `p` refers to "polyfill", while you'd want `a` for partial support.

**Comment by lpd-au** [comment]
My mistake, fixed :)

**Comment by Fyrd** [comment]
Thanks!

**Comment by lpd-au** [comment]
No worries. Do you have a standard test repo/format/library we can use to write tests for immediate inclusion onto the site?

**Comment by Fyrd** [comment]
My tests are at http://tests.caniuse.com with instructions on how to submit at http://tests.caniuse.com/submit.html . Most of the time though for PR features I wind up either rewriting tests or writing tests from scratch. Currently they don't live in a repo though and including tests does not result in immediate inclusion on the site as it's a manual process and can take some time.

**Comment by lpd-au** [comment]
@RByers @patrickhlauke Do you know anyone who'd be happy to OK this so it can go live? See also https://github.com/Fyrd/caniuse/pull/3299

**Comment by RByers** [comment]
The data LGTM, thanks!

**Pull request merged**
