### PR TITLE
#2670 with fixup applied

### PR DESCRIPTION
**Pull request by cvrebert**
Took #2670 and tweaked it to leave in the Chrome feature ID.

### CODE REVIEW

**Comment by ebidel** [comment]
Any progress on getting this merged? Chrome is shipping it soon in 54.

**Comment by Fyrd** [comment]
Currently on vacation, but should get around to more caniuse merges/updates
in a few days

**Comment by ebidel** [comment]
Fwiw my pr fixes this as well and adds a few other things. Have fun on
vacation!

**Comment by cvrebert** [comment]
Closing in favor of #2787.

**Pull request closed without merging**
