### PR TITLE
Update BigInt compactibility of mobile browsers

### PR DESCRIPTION
**Pull request by MuhammedZakir**
Edit: This PR updates Opera Mobile BigInt support, `n` -> `y`.

---

~Android*: 81 -> 67~
~Chrome: 85 -> 67~
~Firefox: 79 -> 68~
~Opera Mobile*: 46 -> 48~
~Samsung Internet: 9.2 -> 9.0~

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Browser_compatibility

* Here, I presume "Opera Mobile" is for Android and "Android Browser" is "Android Webview". Correct me if I am wrong! :-)

### CODE REVIEW

**Comment by atjn** [comment]
Hi there, and welcome to Caniuse :)

Caniuse does not work in the same way as MDN does. When (for example) Firefox 79 is marked `y`, it does not mean that BigInt was added in Firefox 79, but rather that we are only tracking Firefox 79, and that it happens to support BigInt.
It is not currently possible to change the tracked versions, as stated in the [contributing guidelines](https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#unsupported-changes).

If you, like me, think Caniuse should be tracking older versions of mobile browsers, i suggest creating an issue for it or voting for an existing one, like #3518

Specifically when it comes to Opera Mobile, @Fyrd is currently [working on](https://github.com/Fyrd/caniuse/issues/5602) updating the tracked version to `v59`. I suggest removing the other changes and keeping this PR open with the update to Opera Mobile support, then @Fyrd will merge it as soon as he is ready with a full update to all tables. Thanks!

By the way, your presumption is correct 👍

**Comment by MuhammedZakir** [comment]
> Hi there, and welcome to Caniuse :)

:-)

> Caniuse does not work in the same way as MDN does. When (for example) Firefox 79 is marked `y`, it does not mean that BigInt was added in Firefox 79, but rather that we are only tracking Firefox 79, and that it happens to support BigInt.

I take first version marked as "yes" for a feature as the first version of that browser to support it. When someone checks compatibility table, I think that's what they would expect too. So wouldn't this just confuse users? Is there a specific reason for this?

> It is not currently possible to change the tracked versions, as stated in the [contributing guidelines](https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#unsupported-changes).

I didn't connect that to this.

> If you, like me, think Caniuse should be tracking older versions of mobile browsers, i suggest creating an issue for it or voting for an existing one, like #3518

I am confused. Are we tracking specific versions and mentioning whether certain features are supported in them or not (as opposed to how MDN does)? Is that how it is?

> Specifically when it comes to Opera Mobile, @Fyrd is currently [working on](https://github.com/Fyrd/caniuse/issues/5602) updating the tracked version to `v59`. I suggest removing the other changes and keeping this PR open with the update to Opera Mobile support, then @Fyrd will merge it as soon as he is ready with a full update to all tables. Thanks!
> 
> By the way, your presumption is correct 👍

Okay. I will remove them later.

**Comment by atjn** [comment]
>  Are we tracking whether specific versions support a feature or not? As opposed to how MDN does - tracking the first version to support a feature? Is that how it is?

Yes, exactly.

>I take first version marked as "yes" for a feature as the first version of that browser to support it. When someone checks compatibility table, I think that's what they would expect too. So wouldn't this just confuse users?

I think that's a great point, and i suggest that you add it to the discussion in #3518 or somewhere else in the issues section.

> ...Is there a specific reason for this?

In order to not scatter this discussion across different PR's and Issues, please go to #3518 and read [Fyrd's explanation](https://github.com/Fyrd/caniuse/issues/3518#issuecomment-308931205) and ask additional questions there :)

**Comment by atjn** [comment]
Caniuse has been updated to track Opera Mobile v59 now.

**Comment by MuhammedZakir** [comment]
> Specifically when it comes to Opera Mobile, @Fyrd is currently working on updating the tracked version to v59. I suggest removing the other changes and keeping this PR open with the update to Opera Mobile support, then @Fyrd will merge it as soon as he is ready with a full update to all tables. Thanks!
> Caniuse has been updated to track Opera Mobile v59 now.

Updated.

**Comment by atjn** [comment]
Awesome, thanks :)

**Comment by Fyrd** [comment]
Thanks! (and thanks @atjn for the explanations!)

**Pull request merged**
