### PR TITLE
Safari TP 206 adds partial support for the Image Capture API

### PR DESCRIPTION
**Pull request by Schweinepriester**
<https://webkit.org/blog/16186/release-notes-for-safari-technology-preview-206/>:

> - Added support for the [Image Capture API](https://w3c.github.io/mediacapture-image/#imagecaptureapi). ([284447@main](https://commits.webkit.org/284447@main)) (136860809)

I have not tested on https://tests.caniuse.com/imagecapture and https://wpt.fyi/results/mediacapture-image?label=master&label=experimental&aligned=&q=ImageCapture does not have a run with 206 yet, perhaps by the time you check it will be there.

### CODE REVIEW

**Comment by Schweinepriester** [comment]
https://tests.caniuse.com/imagecapture looks better than WPT 😅 

Bildschirmfoto 2024-10-26 um 18 14 32

**Comment by Fyrd** [comment]
Hm, I think until `grabFrame()` is supported it should probably be partial support.

**Comment by Schweinepriester** [comment]
Adjusted!

**Comment by Fyrd** [comment]
Perfect, thanks!

**Pull request merged**
