### PR TITLE
Add a feature for WebAssembly reference types

### PR DESCRIPTION
**Pull request by dschuff**
This is a post-MVP feature extension for WebAssembly. Since its launch, several such extensions have been added to the standard and shipped in browsers. See https://github.com/WebAssembly/proposals and https://webassembly.org/features/

If this example is accepted, I will add additional entries for the other finished and/or in-progress wasm extensions.

Most features can be detected conveniently from https://webassembly.org/features/ (the "Your browser" column in the table shows support for the current browser) which is backed by the wasm-feature-detect library at https://github.com/GoogleChromeLabs/wasm-feature-detect

See also #5687

### CODE REVIEW

**Comment by dschuff** [comment]
I have a couple of open questions here that I hope a reviewer can help me with. 
One is that the specifications for webassembly feature extensions begin their life with an informal-but-detailed overview, written in markdown, which describes the feature in terms of what it adds on top of the existing spec. But when the formal spec is written, it begins as a fork of the full spec with all wasm features to date, and ends by being merged into the full spec. So there's no full formal spec with just the single feature in it; maybe that doesn't matter? Also the overview is likely going to be more useful and understandable for most people anyway. Here I made the "spec" URL be the full formal spec, and also added a link to the overview in addition, but I'm open to other approaches here.

Another question is the category. Right now the base wasm page and this one have categories of "Other" but it might make sense to actually give Wasm its own category, since we expect to keep adding features over time, similarly to JS.

**Comment by dschuff** [comment]
Who should take a look at this? Maybe @Fyrd can, or can suggest someone?

**Comment by Fyrd** [comment]
Thanks, I'm okay accepting this and similar entries. Fixed a few issues, though one remaining one is a missing description, would you mind including one? 

Not too concerned about the specification, whatever seems most helpful to people, I'm fine with using the overview.

As for the category, let's stick with "Other" for now, will consider a dedicated category in the future.

Thanks again!

**Comment by dschuff** [comment]
Done, thanks!. I'll hopefully get a chance to add more wasm features next week.

**Comment by Fyrd** [comment]
Thanks!

**Comment by Fyrd** [comment]
@dschuff I notice you included Edge 16-18 as supporting this feature, which was pre-Chromium Edge. Are you sure those versions have support?

**Comment by dschuff** [comment]
Ah good catch, that may have been a copypasta. Pre-chromium Edge supported MVP wasm but I don't think it supported any extensions.

**Pull request merged**
