### PR TITLE
Add support for text-decoration-thickness

### PR DESCRIPTION
**Pull request by jakezneal**
Haven't quite finished this one yet, but just opening a PR to ask a few questions whilst I finish up browser testing.

### CODE REVIEW

**Comment by jakezneal** [comment]
@Fyrd This will become part of `text-decoration`, but currently exists as it's own property, so at some point it will become obsolete as it's own feature on caniuse.com. At which point the spec for `text-decoration` will need to be updated to include `text-decoration-thickness` as a short-hand property.

This is part of the CSS4 spec, but there doesn't appear to be a category for that, so I've categorised it as CSS. Is there going to be a category for CSS4 added, so that specific features for it can be searched for?

**Comment by Fyrd** [comment]
CSS is appropriate, especially since [there is no CSS4](https://rachelandrew.co.uk/archives/2016/09/13/why-there-is-no-css4-explaining-css-levels/). 

Looking good so far!

**Comment by jakezneal** [comment]
I think that's everything needed—sorry this is my first time contributing to caniuse.com, so I want to make sure everything is correct. If you're happy with everything then feel free to merge in. Otherwise let me know if I need to change anything.

**Comment by jakezneal** [comment]
Hmm, reading through MDN BCD, this might be available in Firefox 69 behind a flag. Let me check and, if needed, update my PR accordingly.

**Comment by jakezneal** [comment]
So according to MDN BCD and Bugzilla, it's available in Firefox 69 behind a flag, but as Firefox 69 isn't out until September 3rd, and the current nightly version is 70, I can't test it until then.

Should I make the relevant amends in line with MDN BCD and Bugzilla, or should I wait until Firefox 69 is released and I can test it?

**Comment by Fyrd** [comment]
Yeah let's just wait until tomorrow to check (sorry, just got back from vacation).

**Comment by Fyrd** [comment]
Seems this feature's data is adequately covered by the MDN BCD table at https://caniuse.com/mdn-css_properties_text-decoration-thickness so I'm going to close this PR. Any updates to that data can be made on this file:
https://github.com/mdn/browser-compat-data/blob/master/css/properties/text-decoration-thickness.json

**Pull request closed without merging**
