### PR TITLE
Add brotli encoding

### PR DESCRIPTION
**Pull request by MayhemYDG**
See #1964.

According to these Firefox 44 should support brotli:
https://bugzilla.mozilla.org/show_bug.cgi?id=366559
http://puu.sh/kB9KG/9d5b3862b1.png

I couldn't find a demo/test server for this unfortunately.
No signal from Edge or WebKit.
https://github.com/MicrosoftEdge/Status/issues/291

### CODE REVIEW

**Comment by MayhemYDG** [comment]
Another proof of support in Firefox 44:
http://bitsup.blogspot.fr/2015/09/brotli-content-encoding-for-firefox-44.html

With a test case:
https://ducksong.com/cgi-bin/nph-bro
As the blog post mentioned:
>[edit note - around Oct 6 2015 the token was changed to br from brotli. The token brotli was only ever deployed on nightly builds of firefox 44.]

So the result in garbled in the latest Firefox but that should change quickly.

**Comment by MayhemYDG** [comment]
Another working test case, this one serves with `content-encoding: brotli` so you can test it in Nightly:
https://http2.cloudflare.com/
From https://groups.google.com/a/chromium.org/d/msg/blink-dev/xdVm8c2GOMQ/R-QXY2UGBwAJ

**Comment by ericlaw1979** [comment]
https://www.bayden.com/test/brotliimg.aspx uses the proper `Content-Encoding: br` token, if that's useful to you in any way.

**Comment by MayhemYDG** [comment]
>Also worth mentioning that Chrome is planning support; see Chrome Bugs: 452335, 472009

Yup, see `"chrome_id":"5420797577396224"`.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
