### PR TITLE
Added STP and Safari 11 added support for HEVC

### PR DESCRIPTION
**Pull request by daytonlowell**

### CODE REVIEW

**Comment by Schweinepriester** [comment]
While hurray, do you have a source for this?

I hoped and searched for this since Apple mentioned HEVC all over the place, but I don't think its in the changelog[1] for example, is it? 

[1] https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html

**Comment by daytonlowell** [comment]
I never found any documentation but I can play the HEVC files from here https://x265.com/hevc-video-files/ in Safari on iOS 11.

**Comment by daytonlowell** [comment]
I added a note to the desktop Safari 11 and TP entries that makes it clear it's only supporteed under macOS High Sierra.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
