### PR TITLE
wasm will be enabled by default in FF 52

### PR DESCRIPTION
**Pull request by chicoxyzzy**
https://bugzilla.mozilla.org/show_bug.cgi?id=1342060

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Do not merge yet please. I'll write here when bugzilla ticket will be closed

**Comment by chicoxyzzy** [comment]
Patch is merged into beta, aurora and nightly a minute ago (see bugzilla ticket)

It's time to merge this PR @Fyrd :)

**Comment by chicoxyzzy** [comment]
Edge is on it's way too https://github.com/Microsoft/ChakraCore/pull/2447

I'll keep an eye on it

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
