### PR TITLE
Webkit #137730 was marked as fixed

### PR DESCRIPTION
**Pull request by mkurz**
See https://bugs.webkit.org/show_activity.cgi?id=137730

Related:
https://github.com/philipwalton/flexbugs/issues/197
https://github.com/philipwalton/flexbugs/issues/84

### CODE REVIEW

**Comment by gsnedders** [comment]
We don't actually know this will be fixed in 10.1; it's not implausible that it's too late for 10.1 at this point, but who knows what Apple will do given they never comment on future product release.

**Comment by Fyrd** [comment]
Yeah, better for now to point out that it's fixed in the latest WebKit Nightly.

**Comment by mkurz** [comment]
I think I will just wait until Safari 10.1 is released, check and then update this pull request if needed. We can keep it open until then.

**Comment by Fyrd** [comment]
Yeah okay.

**Comment by daytonlowell** [comment]
Safari 10.1 shipping in iOS 10.3 and this bug appears to still be present.

**Comment by Fyrd** [comment]
Seems to finally be fixed in Safari 11. Have updated the data manually, so closing this PR.

**Pull request closed without merging**
