### PR TITLE
Add feature/bigint

### LINKED ISSUE #4231: detect bigint / arbitrary precision integers
As subject says, time to include the following ES9 feature on caniuse!
https://developers.google.com/web/updates/2018/05/bigint

### PR DESCRIPTION
**Pull request by styfle**
Fixes #4231

### CODE REVIEW

**Comment by styfle** [comment]
@Fyrd Any idea when this will be available on the website?

**Comment by Fyrd** [comment]
Just added!
https://caniuse.com/#feat=bigint

**Comment by styfle** [comment]
Beautiful, thanks! 👍

**Comment by IamManchanda** [comment]
Link is not working @Fyrd .... Is it deployed?

**Pull request merged**
