### PR TITLE
iOS 13 and macOS 10.15 Catalina support OpenType-CFF2 fonts

### PR DESCRIPTION
**Pull request by litherum**

### CODE REVIEW

**Comment by Fyrd** [comment]
Not according to my tests. What is your source?

**Comment by Fyrd** [comment]
Okay I see now you work on WebKit and fonts and you probably know what you're talking about 😅 Still would be nice to see a test case or something, I'm on 10.15.4 and tried Safari 13.1 and Safari TP and my test at http://tests.caniuse.com/?feat=variable-fonts that passes in Chrome & Firefox still seems to fail.

**Comment by litherum** [comment]
macOS Catalina fails to open SourceSerifVariable-cff2.otf.woff. I've filed an internal bug about it: <rdar://problem/63636353>.

Other CFF2 fonts work, though. For example, if you try AdobeVFPrototype.otf from https://github.com/adobe-fonts/adobe-variable-font-prototype it works great.

**Comment by Fyrd** [comment]
Ah, thanks! Have included that font to the test suite and indeed it passes.

**Pull request merged**
