### PR TITLE
WebGPU is scheduled to arrive in Chrome 113...

### PR DESCRIPTION
**Pull request by haraldreingruber**
... according to https://chromestatus.com/roadmap

### CODE REVIEW

**Comment by Schweinepriester** [comment]
I'm excited as well, so this is a duplicate of https://github.com/Fyrd/caniuse/pull/6548/, sorry!

Though I haven't found a way to ~proof~ test it's actually in 113 - maybe it has been shifted to 114 as they mention in the [intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/VomzPhvJCxI/m/SUhU9Z0vAgAJ)…?

There's https://github.com/gpuweb/cts but that currently appears to match stable Chrome.

**Comment by haraldreingruber** [comment]
> Though I haven't found a way to ~proof~ test it's actually in 113 - maybe it has been shifted to 114 as they mention in the [intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/VomzPhvJCxI/m/SUhU9Z0vAgAJ)…?

I've tested https://webgpu.github.io/webgpu-samples/samples/shadowMapping on Chrome Dev which is currently v113, but I guess there is no guarantee that features won't be postponed before the make it into stable.

**Comment by Schweinepriester** [comment]
but to me that looks the same in stable chrome (110/111), i.e. looks like it's polyfilled…?
(in case it matters: I'm on windows 10)

**Comment by haraldreingruber** [comment]
True. Just saw it as well. Sorry for the confusion.

**Pull request closed without merging**
