### PR TITLE
Creating page for Container Queries — Style Queries

### PR DESCRIPTION
**Pull request by jensimmons**
As discussed in #6297.
No browsers support style queries yet. But there are about to be a lot of tutorials and such for Size Queries in Container Queries... and I expect web developers will start to hear a lot about Style queries in the process.

### CODE REVIEW

**Comment by Fyrd** [comment]
Are there any bugs open for this or any comments indicating interest in implementing this part of the spec? I prefer there to be some sign(s) before adding to caniuse. :)

**Comment by Schweinepriester** [comment]
> Are there any bugs open for this or any comments indicating interest in implementing this part of the spec?

Chromium should be https://crbug.com/1302630 (opened by @chromium & prio 2), if I'm not mistaken :)

**Comment by jensimmons** [comment]
@mirisuzanne You might be interested in weighing in here.

**Comment by mirisuzanne** [comment]
Chromim browsers (I've tested Chrome & Edge Canary) do already have a prototype implemented, behind the 'Experimental Web Platform Features' flag. I'm not sure exactly what version that became available, but I can look into it. Currently, the prototype only supports queries on custom properties.

**Comment by mirisuzanne** [comment]
I'm told that experimental support was added in Canary 107.0.5258.0

**Comment by Schweinepriester** [comment]
<https://twitter.com/Una/status/1629213726481035266>

> 🚨 Style queries are coming to Chrome stable 🚨
>
> As of Chrome 111 (current beta & stable next week) you'll be able to query CSS custom properties values to apply styles to child elements!

@Fyrd it would be good to get this added 0:-)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-container-queries-style . Thanks @jensimmons for getting this one started :)

**Pull request closed without merging**
