### PR TITLE
Update indexeddb.json

### PR DESCRIPTION
**Pull request by dennispost**
Added Safari unique index bug

### CODE REVIEW

**Comment by Fyrd** [comment]
Could you include a link to more details on this bug or at least a bit more information? Thanks.

**Comment by cvrebert** [comment]
Perhaps this refers to https://bugs.webkit.org/show_bug.cgi?id=149107 ?

**Comment by dennispost** [comment]
I can't see the bug in this. 

We just figured it out in development. 

Von meinem iPhone gesendet

**Comment by Fyrd** [comment]
@dennispost Can you provide any more details then? If not I'm going to close this PR.

**Pull request closed without merging**
