### PR TITLE
Add feature policy. Fixes #3570

### LINKED ISSUE #3570: Feature Policy
* Spec: https://wicg.github.io/feature-policy/
* Chrome platform status: https://www.chromestatus.com/feature/5694225681219584

### PR DESCRIPTION
**Pull request by ebidel**

### CODE REVIEW

**Comment by ebidel** [comment]
@Fyrd would love your thoughts on how to best structure this addition. There are several new things being added:

- `Feature-Policy` header
- `allow` attribute on iframes
- JS API (`document.policy`).
- The actual set of feature policies 

I suspect browsers will land these bits at different times. Right now, this PR adds all of these pieces under a blank "Feature Policy" entry, but I can see it being helpful to break things out in a more granular way.

**Comment by Fyrd** [comment]
Thanks Eric! I'm fine starting this one out as a potential umbrella feature, when there's more browser support we can start with notes describing difference of support and go to separate subfeatures if that becomes too confusing.

**Comment by ebidel** [comment]
Any idea when this one might land? I see new features were added on 6/14 but not this one.

**Comment by Fyrd** [comment]
FYI the ones I added on 6/14 were originally submitted as PRs over a year ago. When there's not a lot of votes for a feature or it requires a lot of testing it may be a while before research & add it. 

This one seems pretty straightforward though so I should be able to get to it soon.

**Pull request merged**
