### PR TITLE
Safari TP 158: font-size-adjust, WebCodecs by default and AVIF everywhere 🤯

### PR DESCRIPTION
**Pull request by Schweinepriester**
https://webkit.org/blog/13584/release-notes-for-safari-technology-preview-158/

> Implemented CSS font-size-adjust property ([255927@main](https://commits.webkit.org/255927@main))
> Enabled WebCodecs by default ([256060@main](https://commits.webkit.org/256060@main))
> Enabled AVIF image decoding for macOS Monterey and macOS Big Sur ([255984@main](https://commits.webkit.org/255984@main))

[font-size-adjust](https://tests.caniuse.com/font-size-adjust):

image

[WebCodecs](https://tests.caniuse.com/webcodecs):

image

Same as https://github.com/Fyrd/caniuse/pull/6522 but by default now.

[AVIF](https://tests.caniuse.com/avif):

image

🤯

---

Side note: https://github.com/Fyrd/caniuse/pull/6478 is also ready 0:-)

### CODE REVIEW

**Comment by Fyrd** [comment]
Nice, thanks!

**Comment by Schweinepriester** [comment]
Side note: https://github.com/Fyrd/caniuse/pull/6478 is also ready 0:-)

**Comment by jensimmons** [comment]
Thanks! But wait, why is the support box for AVIF on STP on macOS still only partial support instead of full support?

**Comment by Schweinepriester** [comment]
Because https://github.com/Fyrd/caniuse/pull/6508 - there's a question for you there :) - and also https://github.com/Fyrd/caniuse/issues/6505 are still open and I thought keeping partial until they are resolved would be better instead of potentially switching around.

**Pull request merged**
