### PR TITLE
Chrome is unprefixing -webkit-image-set

### PR DESCRIPTION
**Pull request by Schweinepriester**
https://bugs.chromium.org/p/chromium/issues/detail?id=630597#c57

> Unprefix -webkit-image-set

Potentially even more via https://chromestatus.com/feature/5432024223449088:

> However, our implementation has not been per the spec, as only URL values were accepted for the image, and only resolutions with 'x' as a unit were accepted. This changes our implementation to match the spec, accepting all <image> types or a <string> for the image, and all <resolution> types for the resolution. After these changes, image-set will be unprefixed.

WPT: https://wpt.fyi/results/?label=master&label=experimental&aligned=&q=image-set&view=subtest
As of 2022-12-01 Chrome is at 28 / 83.

EDIT:

Nope, doesn't seem like it, WPT still at 28 / 83.

But it's [110 already](https://bugs.chromium.org/p/chromium/issues/detail?id=630597#c57) (using [this](https://chrome.google.com/webstore/detail/crbug-release-indicator/ppbnemgliamfnlhhnclbibcpbnfdclnn)):

> Status: Fixed (was: Started)
> CANARY 110.0.5452.0

<https://tests.caniuse.com/css-image-set>:

image

### CODE REVIEW

**Comment by Schweinepriester** [comment]
[Or maybe not…?](https://bugs.chromium.org/p/chromium/issues/detail?id=630597#c60)

> Put unprefixed image-set behind a flag

**Comment by yisibl** [comment]
Yes, there's still a lot of testing going on with Chrome at WPT, and it's nowhere near enough to be officially enabled.

**Comment by Schweinepriester** [comment]
Intent to Ship issued now:
- https://twitter.com/intenttoship/status/1599952800640794625
- https://groups.google.com/a/chromium.org/g/blink-dev/c/JXcRP4MJc9I/m/5fxH4xJECQAJ
- https://chromestatus.com/feature/5109745420075008

> Estimated milestones
> 110 Or 111

**Comment by Fyrd** [comment]
Good stuff, funnily enough I was just looking this one up myself recently and was pleasantly surprised to hear it's being unprefixed soon :)

**Pull request merged**
