### PR TITLE
Data for web share api

### PR DESCRIPTION
**Pull request by awebdeveloper**
Find supporting data for web share api in the links

### CODE REVIEW

**Comment by awebdeveloper** [comment]
@Fyrd  can u help me with what is breaking

**Comment by Fyrd** [comment]
@awebdeveloper Looking at https://travis-ci.org/Fyrd/caniuse/jobs/222834016 I see your `"notes"` entry is an object instead of a string.

**Comment by awebdeveloper** [comment]
Ok will send a update next week

**Comment by Fyrd** [comment]
This one still had some issue(s) but I'll go ahead and fix it.

**Comment by awebdeveloper** [comment]
When will it show-up on site

**Comment by Fyrd** [comment]
Once the data has been reviewed and approved.

**Comment by cvrebert** [comment]
Fixes #3538

**Comment by cvrebert** [comment]
Fixes #3254

**Comment by awebdeveloper** [comment]
It's now enabled by default in chrome 61.

https://www.chromestatus.com/features/5668769141620736

**Pull request merged**
