### PR TITLE
Fixing #4095

### PR DESCRIPTION
**Pull request by HM100**
According to [this issue](https://github.com/Fyrd/caniuse/issues/4095), IE implements `:-ms-input-placeholder` as `:placeholder-shown`, not as `::placeholder` so this PR fixes it.

### CODE REVIEW

**Comment by HM100** [comment]
Everything is taken from https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown

**Comment by HM100** [comment]
More changes were done than the Issue requested because Mozilla Firefox 4-18 do not support `:-moz-placeholer` (Which was until V51) as `::placeholder` but as `:placeholder-shown`.

**Comment by Fyrd** [comment]
Thanks!

**Comment by HM100** [comment]
@mattbrundage Because pic says it all 
image
See that in IE whole input is with red bg
image
And in Edge and other browsers, only its placeholder is styled (Input still white bg)
That's why I removed reference

**Pull request merged**
