### PR TITLE
More information about brotli experiment

### PR DESCRIPTION
**Pull request by eustas**
Brotli was enabled for all M50 users.

### CODE REVIEW

**Comment by Fyrd** [comment]
What exactly does "Enabled via Chrome-Variations (92fb4fc2)" mean?

**Comment by eustas** [comment]
"Chrome-Variations" is a technology that allows to control chrome flags.
Open "chrome://version" page and it will show "Variations" section with a list of XXXXXXXX-YYYYYYYY values. XXXXXXXX is a hash of flag and YYYYYYYY represents the flag setting.

**Comment by eustas** [comment]
Ping?

**Comment by Fyrd** [comment]
Okay, got it. Wonder if there's a better way to express that though since I think it would confuse most people like that. Also if it's not enabled by default the value still needs to be `n`. If it is, the value should be `y` without the `d`. (sorry for the delay, on vacation)

**Comment by eustas** [comment]
Oh, sorry, didn't mean to disturb you on vacation.
So, it is now enabled by default, but still some users might need to restart their browser to apply this default.
Going to update PR soon.

**Comment by Fyrd** [comment]
lgtm, thanks!

**Pull request merged**
