### PR TITLE
More fieldset[disabled] compatibility data

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by Fyrd** [comment]
Cool, thanks!

**Comment by cvrebert** [comment]
@Fyrd Likewise. Also, you're down to only 4 remaining potential duplicate issues (among those I flagged): https://github.com/Fyrd/caniuse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+commenter%3Acvrebert+duplicate

**Comment by Fyrd** [comment]
@cvrebert Should be handled now. Thanks again for all that! Oh and I just did the remaining research and publishing of the fieldset[disabled] feature too, so it's on the site.

**Comment by cvrebert** [comment]
@Fyrd Great, thanks! That just leaves some likely-defunct issues where the data is probably already on the site: https://github.com/Fyrd/caniuse/issues?utf8=✓&q=is%3Aissue+is%3Aopen+commenter%3Acvrebert+covered

**Pull request merged**
