### PR TITLE
MutationObserver Chrome Android Updates

### PR DESCRIPTION
**Pull request by zhaoz**
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver
According to this, mobile support is aligned with the desktop support for mutation observer.

### CODE REVIEW

**Comment by zhaoz** [comment]
Seems like chrome android browsers are not supported right now? https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#unsupported-changes

Tell me if this should be dropped and sent via feedback or if browser changes are coming.

**Comment by MayhemYDG** [comment]
Caniuse only lists the current stable version of Chrome for Android for any features.

**Comment by Fyrd** [comment]
Yeah, @MayhemYDG is correct.

**Comment by zhaoz** [comment]
Why is that? Why the different policy here?

**Pull request closed without merging**
