### PR TITLE
Broadcast Channel is implemented now

### PR DESCRIPTION
**Pull request by alippai**

### CODE REVIEW

**Comment by Fyrd** [comment]
@alippai Thanks! Can you leave the Chrome ID? Leaving it results in a link under Resources, which may be of some value to some people.

**Comment by alippai** [comment]
I thought it results in "flag enabled only". How can I change that?

**Comment by Fyrd** [comment]
Nah, that happens when you use `n d` ("d" is "disabed by default").

**Comment by Fyrd** [comment]
Fixed by @cvrebert's PR

**Pull request closed without merging**
