### PR TITLE
Update server-timings data to reflect Safari support

### PR DESCRIPTION
**Pull request by stephenreay**

### CODE REVIEW

**Comment by Fyrd** [comment]
Doesn't seem to pass my test. What's the source for this?

**Comment by stephenreay** [comment]
Opening safari and looking in the network tab? What other test would you expect this to pass?

**Comment by Fyrd** [comment]
Aah, I see. My tests currently only cover the PerformanceServerTiming API as defined at https://www.w3.org/TR/server-timing/#the-performanceservertiming-interface, which Safari does not (yet) support. So will need to change this to partial support as it's limited to manually checking the dev tools.

**Comment by stephenreay** [comment]
I see. I didn't even know there was a JS API for it!

**Comment by Fyrd** [comment]
Great, thanks!

**Pull request merged**
