### PR TITLE
Add ui-serif, ui-sans-serif, ui-monospace and ui-rounded values for font-family

### PR DESCRIPTION
**Pull request by Booligoosh**
Based on issue #5342. This is my first time contributing, so let me know if I need to fix things (although I have read the CONTRIBUTING file).

Test CodePen is here: https://codepen.io/Booligoosh/pen/YzywJBd

The ID is a bit long, but I was unsure what else to use for it.

### CODE REVIEW

**Comment by Fyrd** [comment]
Looks good! Thought about the id, how about `font-family-system-ui-2` ? A bit weird, but it indicates it's a follow up of `font-family-system-ui` while leaving room for us to change what values it refers to if necessary in the future.

**Comment by Booligoosh** [comment]
Oh yeah, that could work. Or how about something like `extended-system-fonts`? Might make it a little clearer what the ID is meant to mean.

**Comment by Fyrd** [comment]
Yeah, agreed that's probably better. Go for it!

**Comment by Booligoosh** [comment]
Done! I've left the title as-is but let me know if you want me to change that as well.

**Comment by Fyrd** [comment]
Oh, and the file needs to end with `.json`

**Comment by Booligoosh** [comment]
Done, sorry about that. Travis is now failing with the following error:
```
Browser version missing: ios_saf 13.0-13.1
```
I split it up into separate fields in the file, since support started in 13.1, but is not there in 13.0:
```
...
"12.2-12.4":"n",
"13.0":"n",
"13.1":"y",
"13.2":"y",
"13.3":"y",
"13.4":"y"
...
```
What should I do about that?

**Comment by Fyrd** [comment]
For iOS the version refers to the OS version, not the browser version. I believe iOS 13 & 13.1 use the same browser engine which is why they're combined. I think iOS 13.4 is where support starts in this case.

**Comment by Booligoosh** [comment]
Ohhh, that makes sense. Thanks for picking that up.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
