### PR TITLE
Update CSS.supports information

### PR DESCRIPTION
**Pull request by erikgaal**
According to https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports#Browser_compatibility, the compatibility in Edge is not complete and should be noted. This PR adds the notes explaining the partial support in Edge.

### CODE REVIEW

**Comment by HM100** [comment]
This also happens to some older versions of chrome and Firefox. Can you mention these browsers as well?

**Comment by erikgaal** [comment]
Hi @HM100, do you happen to have a source for this information that I could refer to?

**Comment by HM100** [comment]
It is on MDN as well. On the same page you linked

**Comment by erikgaal** [comment]
Oh, thank you. I will update the PR.

**Comment by Fyrd** [comment]
Confirmed, thanks!

**Pull request merged**
