### PR TITLE
Firefox 56 will support preloading

### PR DESCRIPTION
**Pull request by danez**
https://developer.mozilla.org/en-US/Firefox/Releases/56

### CODE REVIEW

**Comment by Schweinepriester** [comment]
While hooray, maybe its just partial?

<https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Browser_compatibility>:

> [1] Firefox supports preloading of the following content (as values) —  script, style, image, video, audio, track, font, and fetch. The list of font types Firefox supports preloading of is defined in the fonts media type list (note font/collection is not supported).

<https://bugzilla.mozilla.org/show_bug.cgi?id=1222633>, e.g.:

> We do not support "per-document basis" for now. This is a lot of work that we cannot promise before 57. 

> (chrome supports no-cache as well)

**Comment by danez** [comment]
Okay, so should I mark it as partial? and add a not saying only these certain types are supported?

**Comment by Schweinepriester** [comment]
Maybe. I just wanted to start the discussion, as there apparently is a difference.

@Fyrd, what do you think?

**Comment by danez** [comment]
It looks like `worker`, `object`, `document` and `embed` are not supported by looking at the examples in the spec. https://www.w3.org/TR/preload/#link-element-extensions

**Comment by 0gust1** [comment]
Thanks for the PR.
Android Firefox status could also be updated

**Comment by Fyrd** [comment]
@danez Yeah, I think partial seems appropriate, with a note on what's still to do.

**Comment by danez** [comment]
Ok changed.

**Comment by Fyrd** [comment]
Great, thanks!

**Pull request merged**
