### PR TITLE
Added rel=preconnect resource hint

### PR DESCRIPTION
**Pull request by igrigorik**
Preconnect is available in FF39+ and Chrome 46+.

### CODE REVIEW

**Comment by Fyrd** [comment]
@igrigorik Please check the integration errors on your PRs. Looks like you have additional versions included, version numbers must match the sample file exactly.

**Comment by igrigorik** [comment]
@Fyrd I'm a bit confused.. The validator complains that `and_chr` (Android Chrome, correct?) has an invalid key for '38', and the only key I see in sample-data is 44? How do I indicate that something was added in M38 Chrome for Android?

**Comment by Fyrd** [comment]
@igrigorik You can't. Only the latest is included. I'm considering changing that to be the latest 5 or 10 or something at some point but right now it's just the one.

**Comment by igrigorik** [comment]
@Fyrd ah, I see. It'd be great to get more granularity on mobile browsers... since that's where much of the growth is happening nowadays. Updated all three pulls, lmk if there is anything else.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
