### PR TITLE
Update IE11 support string.includes

### PR DESCRIPTION
**Pull request by PabloCC**

### CODE REVIEW

**Comment by atjn** [comment]
What is your source for this change?

I am not able to reproduce it on Windows 10 1904 with the [Caniuse test](https://tests.caniuse.com/?feat=es6-string-includes):

image

**Comment by PabloCC** [comment]
Hi atjn!

I test IE11 in Windows 10 and  browserstack. It works...

IE11-screenshot

**Comment by atjn** [comment]
Hi PabloCC

Sorry, i completely forgot to say welcome to Caniuse!

It seems like it's only working for you because you are testing it on Google.com, which is loading a polyfill for `string.includes`. I'm guessing you just figured it out as well and that's why you just closed the PR.

Well, anyways thanks for contributing!

**Comment by PabloCC** [comment]
Yes! I realized late my mistake with the polyfill.  

Thank you so much for your help!

**Pull request closed without merging**
