### PR TITLE
Edge supports all the Form features

### PR DESCRIPTION
**Pull request by dstorey**
...since adding the form attribute

### CODE REVIEW

**Comment by Schweinepriester** [comment]
What about <https://caniuse.com/#feat=datalist>?
At least its currently listed as subfeature.

@Fyrd:
If it is relevant, imho Chrome <63 should be partial in <https://caniuse.com/#feat=forms>, too.

**Comment by dstorey** [comment]
We support datalist, just there are so usability issues (I think, the link doesn't exist any more), but I don't think they map to any spec bugs.

**Comment by Fyrd** [comment]
Seems fair to me!

**Comment by Fyrd** [comment]
@Schweinepriester I understand the logic there, but frankly `forms` isn't a terribly useful support table anyway, so making it partial just because one of the 13(!) sub-features has partial support seems a bit unnecessary.

**Pull request merged**
