### PR TITLE
Safari 18.2 enables WebGPU by default

### PR DESCRIPTION
**Pull request by controversial**
On devices running iOS 18.2 beta and macOS Sonoma 15.2 beta, WebGPU is marked as “stable” within Feature Flags, and is enabled by default [[1]](https://twitter.com/lukedeentaylor/status/1856092008084812155)

However, I haven’t seen an official announcement of this and it’s not included in the [release notes](https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes) for Safari 18.2—maybe @jensimmons can confirm this change?

Screenshot 2024-11-11 at 5 24 53 PM

### CODE REVIEW

**Comment by controversial** [comment]
See also #7093, #7127

**Comment by jensimmons** [comment]
We’d love for people to test Web GPU, and provide feedback at http://feedbackassistant.apple.com. 

It might be a bit early for it to appear on Can I Use, since it's not listed in release notes. Let me get back to you on that. Thanks for asking.

**Comment by controversial** [comment]
Thanks for the response Jen!

I proposed the change here because WebGPU _is_ enabled by default in stable Safari (i.e. not TP) on my devices running 15.2/18.2, and this wasn’t true on previous macOS/iOS versions.

Looking forward to hearing back; I’m very excited for WebGPU to land in Safari!

**Comment by jensimmons** [comment]
Safari 18.2 beta 4 came out today. If you test in a more recent beta, you'll see that WebGPU is off by default.

**Comment by jensimmons** [comment]
I’ll say again… WebGPU can be [enabled with the feature flag](https://developer.apple.com/documentation/safari-developer-tools/feature-flag-settings). To anyone who reading this who is interested, please do test it out! File any issues you find at [bugs.webkit.org. ](https://bugs.webkit.org) (where you can now log in using your GitHub account) and help us ensure it’s awesome.

**Comment by jensimmons** [comment]
I don't have an answer about when. It is close, but we want to make sure it's ready before shipping.

**Pull request closed without merging**
