### PR TITLE
Add Async Clipboard API

### LINKED ISSUE #4031: Asynchronous Clipboard API (replaces document.execCommand)
Currently it's not supported as it's experimental, but it's intended to replace the `document.execCommand` method to manage the clipboard. The return value is a Promise.
Here is the draft from [W3C](https://w3c.github.io/clipboard-apis/)
Here is the docs from the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)

### PR DESCRIPTION
**Pull request by danielcompton**
The Clipboard API spec has two parts, an older synchronous document.execCommand based API, and a newer asynchronous clipboard API. These are sufficiently different in support and usage that I think it may make sense to split them into two different features.

This is my first addition, so let me know if I've gotten this wrong. I suspect there are some caveats needed to be added to the Chrome support:

> As you may have noticed, this post only covers the text part of navigator.clipboard. There are more generic read() and write() methods in the specification, but these come with additional implementation complexity and security concerns (remember those image bombs?).  - [Unlocking Clipboard Access](https://developers.google.com/web/updates/2018/03/clipboardapi#whats_next_for_the_async_clipboard_api)

I'm not quite sure what/how that should be phrased though, @developit, could you help here?

Fixes #4031

### CODE REVIEW

**Comment by Fyrd** [comment]
Looks good, though I'd prefer to leave the ID (filename) of the original what it was.

**Comment by danielcompton** [comment]
Great, I’ve done that now.

**Comment by Fyrd** [comment]
Thanks!

**Comment by danielcompton** [comment]
Is there anything I can do to help with this, or is it currently waiting on https://tests.caniuse.com tests to be implemented?

**Pull request merged**
