### PR TITLE
WIP Add note for IE11 about assign to classList

### PR DESCRIPTION
**Pull request by RusinovAnton**
refs: https://github.com/Fyrd/caniuse/issues/3808

TODO:
- [ ] - test other browsers

### CODE REVIEW

**Comment by Fyrd** [comment]
Want me to merge this now or wait until other browsers have been tested too?

**Comment by RusinovAnton** [comment]
I think it could be another PR with tested browsers so you can merge this one

**Comment by dstorey** [comment]
classList is read only per spec, but now there is a putForward=value which puts forward the value to set value on DOMTokenList (not actually classList) instead. I implemented this in the upcoming version of Edge.

**Comment by RusinovAnton** [comment]
@dstorey Nice. I would be really grateful if you could give me reference where I could any see info, discussion etc on why this implemented that way.

**Pull request merged**
