### PR TITLE
Firefox 41 fires copy/cut/paste for empty selection

### PR DESCRIPTION
**Pull request by Yaffle**
after `Ctrl+C`/Ctrl+X/Ctrl+V or after document.execCommand('copy')/...

### CODE REVIEW

**Comment by Fyrd** [comment]
Doesn't seem to work for me...do you have a test case?

**Comment by Yaffle** [comment]
https://jsfiddle.net/pq6hx0qj/2/

**Comment by Yaffle** [comment]
https://jsfiddle.net/pq6hx0qj/4/

**Comment by Fyrd** [comment]
@Yaffle Okay, cool, thanks. That doesn't seem to cover paste though, correct?

**Comment by Yaffle** [comment]
@fbender , well, yes, Firefox does not fire "paste", Chrome does...

**Comment by fbender** [comment]
@Yaffle I think you mentioned the wrong user, just FYI. 

Further FYI: https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/ and zeroclipboard/zeroclipboard#171

**Comment by Yaffle** [comment]
@fbender , sorry, the list of suggestions sorts names strangely...
Thanks for the links, I have been reading them already...

**Comment by Fyrd** [comment]
Okay, I've added some new notes to clarify. Getting kinda noisy now but I guess that's better than incorrect data. Thanks for reporting!

**Comment by Yaffle** [comment]
@Fyrd , thanks! I am relying on Ctrl+C for empty selection in my webapp, so I hope other browsers fix this.

**Pull request closed without merging**
