### PR TITLE
Add #rrggbbaa feature.

### PR DESCRIPTION
**Pull request by ben-eb**
Ref: https://github.com/Fyrd/caniuse/issues/2249

### CODE REVIEW

**Comment by jhpratt** [comment]
Reporting Chrome 53 on mobile has no support for 4 or 8 digit hex codes.

**Comment by Fyrd** [comment]
Thanks!

**Comment by Fyrd** [comment]
@ben-eb FYI just did some testing and it's not in fact enabled by default on Chrome. In the future please test feature support where possible.

**Comment by ben-eb** [comment]
Ah, my mistake, I'm running Chrome with the experimental web platform features flag. Will make sure to disable this when submitting future pull requests.

**Comment by Fyrd** [comment]
Ah yeah, I've made that mistake before myself. Anyway, feature's up now. :)

**Comment by jhpratt** [comment]
@Fyrd What do you use for browser testing? Obviously I can get some, but I imagine it isn't just downloading all the browsers. I'd be willing to go through pending PRs and verify data if you'd like.

**Pull request merged**
