### PR TITLE
Adding CSS4 hyphenate entry

### PR DESCRIPTION
**Pull request by KurtPreston**
For issue #2155.

Couldn't find much information on current support besides the table written up here:
http://webdesign.about.com/od/fonts/a/hyphenation-in-css3.htm

I can confirm that `-webkit-hyphenate-character` works in Chrome 55 and up.

### CODE REVIEW

**Comment by Fyrd** [comment]
"CSS4" is not a valid category. I recommend just using "CSS".

**Comment by KurtPreston** [comment]
@Fyrd Just pushed a change adding CSS4 as a valid category.  Seems like it should be, since CSS3 is used as a category and CSS4 has a working draft.  If you'd prefer though, I can just remove the tag instead.

**Comment by Fyrd** [comment]
Ah, nice try, but [CSS4 is not a thing](http://www.xanthir.com/b4Ko0). Also categories are managed elsewhere, new categories can't just be added by PR.

If anything I'd like to remove the CSS2 & 3 categories at some point.

**Comment by KurtPreston** [comment]
K, I've pushed an update that just changes the category "CSS".

But for the record, CSS4 is totally a thing.  The article you linked to was published in 2013.  W3C's CSS4 spec was posted in 2015:
https://www.w3.org/TR/css-text-4/

**Comment by Fyrd** [comment]
Thanks!

Level 4 != CSS4 though. Here's a newer article if you don't believe me. :)
https://rachelandrew.co.uk/archives/2016/09/13/why-there-is-no-css4-explaining-css-levels/

**Comment by Fyrd** [comment]
Oh, and more specifically:
https://www.w3.org/TR/CSS/#css-level-4

**Comment by KurtPreston** [comment]
Hehe, should have known better than to dispute the maintainer of CanIUse.  Thanks for the clarification, and thanks for your excellent project!

**Pull request merged**
