### PR TITLE
Enable credential management api

### PR DESCRIPTION
**Pull request by agektmr**

### CODE REVIEW

**Comment by Fyrd** [comment]
Not quite that simple...I only enable features once they've been reviewed. Thankfully this one was fairly straightforward so I went ahead and did the review and have just enabled it manually.

**Comment by agektmr** [comment]
@Fyrd For future reference, how does review process work? I've been waiting for this to be enabled expecting you enable it on your side.

**Comment by Fyrd** [comment]
@agektmr I review submitted features when I get around to them. The quality of some submissions is quite poor and it can take a lot of time to essentially redo all the research. Especially for features with [few votes](http://caniuse.com/issue-list/) it doesn't seem right to spend time on them rather that adding features that many people have asked for. So it can take a while, since it's often unclear from the beginning how much extra research may be required.

**Comment by agektmr** [comment]
Great to know. Thanks!

**Pull request closed without merging**
