### PR TITLE
Adding CSS zoom property

### PR DESCRIPTION
**Pull request by pkuczynski**
Fixing #1453, #1545, #1285, #1053

### CODE REVIEW

**Comment by Fyrd** [comment]
There's a few issues here, the spec link is wrong, the spec status is wrong and there's a link entry without values.

If there's not a specification that includes this property I suggest using the MSDN link there.

**Comment by pkuczynski** [comment]
I pushed this too early, sorry! Fixes applied...

**Comment by Fyrd** [comment]
Thanks! I'm currently on vacation so it may take a week or so before I'm able to verify the information and publish it to the sit.

**Comment by pkuczynski** [comment]
No rush! Enjoy your holiday :)

**Comment by Fyrd** [comment]
@pkuczynski Okay, it's on the site now. I should note that a number of corrections were needed, seems `zoom` is still supported in all newer IE and mobile IE as well as any other mobile WebKit browser. As I believe I have mentioned before, if you do not know the support, use the `u` value, not `n`.

**Comment by pkuczynski** [comment]
Regarding IE, I read about it somewhere, but can't find it now. I should check it more deeply, sorry. Will try better next time. However which webkit browsers I skipped? I thought I marked all of them correctly?

**Comment by Fyrd** [comment]
The BlackBerry browsers and UC browser are all WebKit-based (actually I think BB10 might use Blink). Again, I don't expect everyone to test those browsers, but they're more likely to match say a slightly older version of Safari than anything else.

**Comment by pkuczynski** [comment]
Got it.

**Pull request merged**
