### PR TITLE
[CSS text-rendering] Update unoff spec link to CR

### PR DESCRIPTION
**Pull request by Malvoz**
There's also a SVG2 draft spec on a new location (https://svgwg.org/svg2-draft/), I don't know if the CR will move to that location in the future... I would assume it is not preferred over the CR though.

### CODE REVIEW

**Comment by Malvoz** [comment]
Hey.. I'm new to this 😉

**Comment by Fyrd** [comment]
It's a bit confusing, but this feature is actually about using the property in HTML for the purpose of enabling high-quality kerning and ligatures, not the behavior in SVG. As the behavior in HTML is unspecified (see the note at https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering), the status is considered "unofficial".

**Comment by Malvoz** [comment]
You're right, how silly of me not to realize that. I should pay more attention, I roam alot of specs. 

Anyhow, the updated link in this PR points to https://www.w3.org/TR/SVG2/ which is the successor of  https://www.w3.org/TR/SVG11/

**Comment by Fyrd** [comment]
I've just updated the link as well as the description, it should be a bit more clear now what this feature is about and the status of the property. Thanks!

**Pull request closed without merging**
