### PR TITLE
Safari 16.4 & TP: Declarative Shadow DOM?

### PR DESCRIPTION
**Pull request by Schweinepriester**
- https://twitter.com/rniwa_dev/status/1611504775375519744
- https://github.com/WebKit/WebKit/commit/36f99b7c366702e9827a0d33989eb3b27eaa301a
- https://bugs.webkit.org/show_bug.cgi?id=249513

Safari TP 162 is here:
* https://twitter.com/webkit/status/1618362420250161154
* https://webkit.org/blog/13703/release-notes-for-safari-technology-preview-162/

> Enabled declarative Shadow DOM by default ([258566@main](https://commits.webkit.org/258566@main), [258568@main](https://commits.webkit.org/258568@main))

<https://tests.caniuse.com/declarative-shadow-dom> however is still red:

image

WPT [shows progress](https://wpt.fyi/results/shadow-dom/declarative?label=master&product=chrome%5Bexperimental%5D&product=firefox%5Bexperimental%5D&product=safari%5Bstable%5D&product=safari-162+preview%5Bexperimental%2Cazure%5D&aligned=&view=subtest&q=shadow+dom):

image

But I don't know, should TP be `y` or partial…? Where's the line? 🤔
Opening the PR though for discussion.

### CODE REVIEW

**Comment by e111077** [comment]
There might be need for a note here on all previous and current `y`'s: The spec for DSD changed from having `<template shadowroot="open">` (non-streaming) to `<template shadowrootmode="open">` (streaming) which is what Safari TP and Chrome Canary have both implemented. [Context](https://groups.google.com/a/chromium.org/g/blink-dev/c/xzT-vN-bx0s)

**Comment by kiding** [comment]
image

Confirmed `shadowrootmode` (streaming) works with Safari TP using Local Override. We can put a note to **Chrome <111 (& Edge)** (Ref: [Chrome Platform Status](https://chromestatus.com/feature/5161240576393216)) saying they do not support streaming and `shadowrootmode` attribute.

**Comment by Schweinepriester** [comment]
Mentioned in https://web.dev/web-platform-02-2023/ as well:

> Also in Chrome 111 is the [declarative shadow DOM](https://developer.chrome.com/articles/declarative-shadow-dom/), a new way to implement and use shadow DOM directly in HTML.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
