### PR TITLE
Add data for tabindex attribute

### LINKED ISSUE #1062: Browser support for the HTML5 implementation of negative tabIndex values
Browser support for the HTML5 implementation of negative tabIndex values (to indicate elements that should be left out of the tabIndex) is apparently spotty/irregular. So I came here to see what browsers supported it partially/fully... &quot;Not Found&quot; :(

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __Bleus__ on __2014-09-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #1062.

Testcases:
* http://output.jsbin.com/hemahu/quiet
* http://output.jsbin.com/qikubi/quiet

Programmatic focusing of elements with negative tab indices works in Android 4.0 and iOS 7.1, but it's not obvious how to test the tabbing order on mobile devices.

### CODE REVIEW

**Comment by Fyrd** [comment]
Looking at the support level I'm tempted to add this to the "supported everywhere" list but I guess the OSX notes etc may be of use to those confused, so...eh, why not. Thanks!

**Comment by cvrebert** [comment]
Well, hey, it got 25 votes, so... 😄

**Comment by Fyrd** [comment]
Good point!

**Comment by cvrebert** [comment]
I honestly can't fathom what the OP meant then they said

> Browser support for the HTML5 implementation of negative tabIndex values (to indicate elements that should be left out of the tabIndex) is apparently spotty/irregular.

The OS X thing is the only irregularity I could some up with.

**Comment by Fyrd** [comment]
@cvrebert Is there a reason you marked the latest Chrome, Firefox & Android versions as supported? They would seem to suffer the same lack of tabbability as on other mobile devices.

**Comment by cvrebert** [comment]
@Fyrd As I mentioned in the description, I didn't test tabability on mobile devices (how does one even "Tab" on them? I'd guess you'd need to use some assistive tech. interface), only programmatic focusability there.

**Comment by Fyrd** [comment]
@cvrebert Right, but for example you marked the latest Chrome on Android as "y" rather than "u" like most other mobile browsers, I was curious if that distinction was deliberate.

**Comment by cvrebert** [comment]
The obscure mobile browsers were "u" because I don't have access to them to test them.

**Comment by Fyrd** [comment]
And...the less obscure iOS versions? :)

**Pull request merged**
