### PR TITLE
CSS Variables: Info: polyfill for IE11

### PR DESCRIPTION
**Pull request by nuxodin**

### CODE REVIEW

**Comment by Fyrd** [comment]
Thanks!

**Comment by TimVevida** [comment]
The mentioned polyfill has only been available for 14 days, and is on CanIUse already? It doesn't even have a stable release version. I don't know what the quality of the code is, but this seems a bit premature.

**Comment by nuxodin** [comment]
Hello, I'm the writer.
I'm sure you won't find a better Polyfill. Otherwise I will gladly let you show me a better one.
CSS Custom Properties are not so easy to polyfill, I think I did a good job there. Did you test the script?

**Comment by nuxodin** [comment]
I made a NPM packege.
Would be happy to receive your feedback or your improvements.

**Comment by nuxodin** [comment]
https://www.npmjs.com/package/ie11-custom-properties

**Pull request merged**
