### PR TITLE
web-share: Fix support data for Chrome and Chrome on Android

### PR DESCRIPTION
**Pull request by Turbo87**
The just released Chrome 61 enabled the feature by default but from https://www.chromestatus.com/feature/5668769141620736 it looks like the feature is only available on Android at this point. (My Chrome 61 on desktop doesn't know about `navigator.share` either)

### CODE REVIEW

**Comment by Schweinepriester** [comment]
Sadly per <https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#unsupported-changes>:

> ### Unsupported changes
> 
> Currently it is not possible to:
> * Add a new browser or browser version

You are correct though, <https://www.chromestatus.com/feature/5668769141620736> only states:

> Enabled by default (launch bug) in:
Chrome for Android release 61

**Comment by Turbo87** [comment]
@Schweinepriester good point, apparently I missed that. how can we move this forward?

**Comment by Fyrd** [comment]
This has been taken care of, so closing.

**Comment by Turbo87** [comment]
alright, thanks :)

**Pull request closed without merging**
