### PR TITLE
Update Chrome support status for image/iframe lazy loading

### PR DESCRIPTION
**Pull request by phanan**
Chrome 76 has added default support for image/iframe lazy loading: https://twitter.com/hdjirdeh/status/1158984255214460928.

### CODE REVIEW

**Comment by Schweinepriester** [comment]
While <https://www.chromestatus.com/feature/5645767347798016> also states this, it doesnt seem to work everywhere:

image

Links:
- <https://tests.caniuse.com/?feat=loading-lazy-attr>
- <https://mathiasbynens.be/demo/img-loading-lazy>

---

Chrome Canary

> Version 78.0.3876.0 (Offizieller Build) canary (64-Bit)

works though.

**Comment by ganchito55** [comment]
I have the same setup as @Schweinepriester but for me it's enabled:
imagen

**Comment by Schweinepriester** [comment]
I just checked again (still `Version 76.0.3809.100 (Offizieller Build) (64-Bit)`) and now it works oO Even though yesterday I double checked by restarting before posting…

LGTM +1 and disregard my comment I guess.

**Comment by karlhorky** [comment]
I think it was not enabled in the first `76` versions, but has been enabled in a recent update.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
