### PR TITLE
Add background-clip support for text value

### PR DESCRIPTION
**Pull request by jmmarco**
Adding support for `background-clip: text`

### CODE REVIEW

**Comment by ai** [comment]
Should we rename the file to `background-clip-text.json`?

@Fyrd we need this JSON for Autoprefixer https://github.com/postcss/autoprefixer/issues/1081

**Comment by jmmarco** [comment]
@ai sure, that sounds good.. Done.

**Comment by Fyrd** [comment]
Thanks!

**Comment by jmmarco** [comment]
@Fyrd I updated the support coverage for Edge 15+. How should I get this to you? Should I send the updated PR over to you?

**Comment by ai** [comment]
@jmmarco you should create another PR for it.

**Pull request merged**
