### PR TITLE
feat: add subresource-bundling

### PR DESCRIPTION
**Pull request by jeffkaufman**
Chrome 104 enabled `<script type=webbundle>`.  See https://chromestatus.com/feature/5710618575241216

### CODE REVIEW

**Comment by Fyrd** [comment]
@jeffkaufman No missing steps, though if you could include a test of any kind in which to detect this feature that would be helpful!

**Comment by jeffkaufman** [comment]
@Fyrd is the https://www.jefftk.com/wbn-demo/ link the kind of test you mean?

**Comment by Fyrd** [comment]
Yup, that'll do. Thanks!

**Comment by Fyrd** [comment]
btw, is this the same feature as https://github.com/Fyrd/caniuse/issues/6047 ?

**Comment by hayatoito** [comment]
#6047 seems a bit ambiguous. That doesn't mention any particular feature. It's just about Web Bundle format itself? 

This PR is about "Subresource Loading with Web Bundles", which is the actual feature which uses Web Bundle format to load subresources from there in Web.

**Comment by jeffkaufman** [comment]
I agree that #6047 is more general and not quite the same as this. For example, I would interpret #6407 as including being able to navigate a top level browsing context to a web bundle.

**Comment by jeffkaufman** [comment]
Thanks for the merge!

**Pull request merged**
