### PR TITLE
SHA-2

### PR DESCRIPTION
**Pull request by jhpratt**
#2884

### CODE REVIEW

**Comment by Fyrd** [comment]
Can you include a description? Thanks!

**Comment by jhpratt** [comment]
Not quite sure what you'd like; I think it's pretty self-explanatory.

**Comment by Fyrd** [comment]
All features need a description. How about something like: "Security certificate for SHA-2: a set of cryptographic hash functions which includes SHA-224, SHA-256, and SHA-512" (via your globalsign.com link)

**Comment by jhpratt** [comment]
Just added that in.

**Comment by Fyrd** [comment]
Thanks!

**Pull request merged**
