### PR TITLE
Same-Site-Cookie is implemented in FF >= 58

### PR DESCRIPTION
**Pull request by TorbenF**
Mozilla closed https://bugzilla.mozilla.org/show_bug.cgi?id=1286858

### CODE REVIEW

**Comment by Fyrd** [comment]
Thanks!

**Comment by TorbenF** [comment]
Just saw it got reverted. What's wrong with it?

**Comment by Fyrd** [comment]
Sorry, that was by mistake. Will get it restored.

**Comment by Fyrd** [comment]
And fixed!

**Comment by TorbenF** [comment]
Thank you!

**Pull request merged**
