### PR TITLE
Add more Android/Chrome Pointer Events data points

### PR DESCRIPTION
**Pull request by patrickhlauke**

### CODE REVIEW

**Comment by cvrebert** [comment]
Additional Android Chrome versions can't currently be added.
See https://github.com/Fyrd/caniuse/pull/1920#r39089362

**Comment by patrickhlauke** [comment]
Current stable version of Chrome/Android is 53...so how/when can new versions be added / when will it update?

**Comment by Fyrd** [comment]
I'll update it to 53 shortly.

**Comment by Fyrd** [comment]
Have updated the version and the data for this entry. Thanks!

**Comment by patrickhlauke** [comment]
Perfect, thank you :)

**Pull request closed without merging**
