### PR TITLE
Safari 16 and STP fixed display: contents bug

### PR DESCRIPTION
**Pull request by jensimmons**
Safari 16 and STP fixed the display: contents accessibility bug, so now they both have full support.

- Added accessibility support for display:contents.
https://developer.apple.com/documentation/safari-release-notes/safari-16-release-notes

### CODE REVIEW

**Comment by Schweinepriester** [comment]
@hidde and I talked about that there: https://twitter.com/schweinepriestr/status/1521232478295498752

That resulted in

> Update 3 May 2022: an ’initial fix‘ for this problem was [added in Safari Technology Preview 144](https://webkit.org/blog/12621/release-notes-for-safari-technology-preview-144/); at the time of writing this was not yet in your user's browsers, but it will be for many in the near future

on https://hidde.blog/more-accessible-markup-with-display-contents/.

Since https://bugs.webkit.org/show_bug.cgi?id=185679 is still (re)opend I'm not sure about full support...?

**Comment by hidde** [comment]
So glad to see this, seems to me like this could be merged and I'll have to update my post again now that Safari 16 was announced 🎉

Thanks for all your work on this @jensimmons

**Comment by Schweinepriester** [comment]
Apologies to (continue to) nag, I'm the last one not wanting to paint it green and it's great to see progress 🎉, but does [#185679](https://bugs.webkit.org/show_bug.cgi?id=185679) not prevent full support?
It's mentioned in https://hidde.blog/more-accessible-markup-with-display-contents/

> The list shows as ‘no accessibility information’ ([Safari bug](https://bugreport.apple.com/web/?problemID=39630240), [Webkit bug #185679](https://bugs.webkit.org/show_bug.cgi?id=185679), [Webkit bug #237834 that they did more work in](https://bugs.webkit.org/show_bug.cgi?id=237834))

(the middle one).

**Comment by jensimmons** [comment]
There is a bit of rework still being done. But before filing this PR, I asked our accessibility engineers if the fixes that are shipping in Safari 16 meant we want to recommend to web developers to start using `display:contents`. Have we fixed the “severe implementation bug that renders the content inaccessible”? They said yes. It's time. The main problem is fixed.

**Comment by Schweinepriester** [comment]
Alright then, thank you!

**Comment by hidde** [comment]
Great news!

**Comment by Fyrd** [comment]
Great news indeed, thanks!

**Pull request merged**
