### PR TITLE
Add passkeys to Can I Use

### PR DESCRIPTION
**Pull request by jensimmons**
Creating the JSON file to add passkeys to Can I Use, to fulfill https://github.com/Fyrd/caniuse/issues/6450

### CODE REVIEW

**Comment by jensimmons** [comment]
Once again, I have an error in the new file I'm trying to create. I often don't know how to handle the formatting of notes/bugs/resources when those fields are empty. 

Thoughts @Schweinepriester ?

**Comment by Fyrd** [comment]
@jensimmons If you look at the validator result ("Details" link) you'll see the error `"Error: [passkeys] Failed hasCategories validation on "categories". Got this: Web API,security"`. I believe the categories should be `["JS API", "Security"]`.

I think you'll also want to leave the `parent` value as empty string and set any necessary `keywords` to something other than the sample default.

**Comment by Fyrd** [comment]
It would also be great to have a way to test support for this to easily tell when support is added in other browsers. I looked around a little bit but wasn't able to find anything simple yet.

**Comment by jensimmons** [comment]
I just asked our engineers if there's a demo from FIDO Alliance that could serve as a great test, but it seems like not. 

They did clarify that supporting passkeys includes:
1. User-verifying platform authenticator
2. Support for “conditional mediation” in CredMan
3. Platform it’s running on supports cross-device sign-in via the hybrid transport
4. Credentials are backed up and/or synced

**Comment by ptman** [comment]
https://www.passkeys.io/ - has a demo, but aren't passkeys just using the WebAuthn API? So if you support WebAuthn at a specific level, you support passkeys? https://github.com/Fyrd/caniuse/issues/5649

**Review by ptman — APPROVED** [review]

**Comment by jensimmons** [comment]
Passkeys are now supported in Chrome 108+

https://blog.chromium.org/2022/12/introducing-passkeys-in-chrome.html

**Comment by jensimmons** [comment]
> aren't passkeys just using the WebAuthn API? So if you support WebAuthn at a specific level, you support passkeys?

No. WebAuthn is part of the stack -- the part a web developer codes.But support for passkeys is much more complex than that. It goes deeper into the underlying operating system, often involving security and various kinds of biometric credential management. 

I wish Can I Use would be willing to add a page for this. Web developers should be implementing passkey support on their websites and web apps, but there is not good data available on which browsers on which operating systems have support. Not having the resources developers need holds back the web from replacing passwords with a far more secure way to log in.

**Comment by Fyrd** [comment]
Have merged & updated this PR, though still in the process of testing support and updating information about the feature. In particular I think notes may be necessary on different behavior for different OSes? Further help would certainly be appreciated.

**Comment by Fyrd** [comment]
Wound up linking to https://passkeys.dev/device-support/ in the notes, seems pretty comprehensive.

**Pull request merged**
