### PR TITLE
Add document.head

### LINKED ISSUE #1052: The HTML5 document.head DOM tree accessor
The HTML5 document.head DOM tree accessor

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __Mathias Bynens__ on __2011-08-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #1052.
Testcase: http://jsfiddle.net/cvrebert/ggoyfq61/

### CODE REVIEW

**Comment by Fyrd** [comment]
@cvrebert I think we can do without `document.body`, that one's been around forever compared to `document.head` which was only introduced with HTML5. Thanks!

**Comment by cvrebert** [comment]
@Fyrd Fair point. Done.

**Comment by cvrebert** [comment]
Maybe add a "Yes, everywhere" notice for `document.body`?

**Comment by Fyrd** [comment]
Yeah, definitely. Thanks!

**Pull request merged**
