### PR TITLE
Update prefers-color-scheme.json

### PR DESCRIPTION
**Pull request by lacroixlucas59**

### CODE REVIEW

**Comment by Malvoz** [comment]
Can you provide documentation?

**Comment by lacroixlucas59** [comment]
Aviable in the version 61.0.3298.3 the 2019-04-30

https://blogs.opera.com/desktop/changelog-for-61/

**Comment by Malvoz** [comment]
Thanks!

**Comment by Fyrd** [comment]
Confirmed, thanks!

**Pull request merged**
