### PR TITLE
Details & Summary landed in Fx47 behind pref

### PR DESCRIPTION
**Pull request by mpopp75**
Details and Summary are now (as of February 5th) available in Firefox 47 behind dom.details_element.enabled preference.

### CODE REVIEW

**Comment by mpopp75** [comment]
I can't find why the checks fail, looks alright to me.

Any clues?

**Comment by Fyrd** [comment]
Needs to be "n d #1" :)

**Comment by mpopp75** [comment]
Thanks, I added the commit.

**Comment by Fyrd** [comment]
:+1:

**Pull request merged**
