### PR TITLE
Add margin-start data

### PR DESCRIPTION
**Pull request by ai**
Data for `margin-start`, `margin-end`, `padding-start`, `padding-end` according [MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-padding-start).

### CODE REVIEW

**Comment by ai** [comment]
@Fyrd This PR is required for Autoprefixer 5.1 release https://github.com/postcss/autoprefixer/issues/324

**Comment by ai** [comment]
@Fyrd hm, seems my fork is too old. But I afraid to remove my fork and refork it, becuase of resolution PR. Can you fix `and_chrome 40` issue on merge? Or I can fix it after resolution PR merge.

**Comment by Fyrd** [comment]
Yeah, I'll fix it.

**Comment by ai** [comment]
@Fyrd can you please release npm?

**Comment by Fyrd** [comment]
@ai Done!

**Pull request merged**
