### PR TITLE
Add const and let from ES6

### LINKED ISSUE #1493: javascript 'let' and 'const' functions/statements are not supported across all browse...
javascript &#39;let&#39; and  &#39;const&#39; functions/statements are not supported across all browsers, and are critical in recursive environments for straightening out closures and function objects.  A support table would be helpful!

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __themolecule__ on __2012-02-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

### PR DESCRIPTION
**Pull request by dstorey**
fixes #1493

### CODE REVIEW

**Comment by Fyrd** [comment]
Very nice, thanks!

**Comment by Fyrd** [comment]
@dstorey I'm not sure if the "const is recognised outside of strict mode, but is treated like var" note applies to current Chrome...in [this test](http://codepen.io/Fyrd/pen/WQNQNd) when attempting to change a const value it does not succeed (as it would if it was treated like var).

**Comment by dstorey** [comment]
@fyrd looking into it. It fails http://kangax.github.io/compat-table/es6/#const_redefining_a_const_is_an_error at least.

**Comment by Fyrd** [comment]
Yeah, it doesn't throw an error, just doesn't overwrite it. Wonder if that applies to all no. 1 note browsers.

**Comment by dstorey** [comment]
@Fyrd the not being block scoped is certainly true. Does "success!" twice in Chrome/Safari 9 http://jsfiddle.net/upv41153/

**Comment by dstorey** [comment]
#1 is correct for Firefox 1–12 at least. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const 

That doc says reassignment fails in Chrome 20+, although it looks like it still isn’t block scoped

(sadly my BrowserStack run out so don't have full range of browsers to check right now)

**Comment by dstorey** [comment]
…and like you said it doesn't throw error like it should (and does in FF/Edge) (http://jsfiddle.net/o56u9g2e/)  so doesn't pass at least.

**Pull request merged**
