### PR TITLE
Firefox actually removed HTML Imports flag in M56 + Fixing something

### PR DESCRIPTION
**Pull request by HM100**
https://bugzilla.mozilla.org/show_bug.cgi?id=1197401

### CODE REVIEW

**Comment by HM100** [comment]
Oops! Accidentally did that

**Comment by Fyrd** [comment]
Thanks!

**Comment by HM100** [comment]
Then why did you revert my PR along with another PR. I had done to reflect MDN and my test but you seem to revert it. Why? @Fyrd

**Comment by Fyrd** [comment]
@HM100 Sorry about that, those changes have been restored now. Thanks for pointing it out!

**Comment by HM100** [comment]
Ok

**Pull request merged**
