### PR TITLE
Safari TP 15: Download attr, KeyboardEvent.*

### PR DESCRIPTION
**Pull request by Schweinepriester**
Should have catched everything from <https://webkit.org/blog/6987/release-notes-for-safari-technology-preview-15/> which is already on caniuse.

### CODE REVIEW

**Comment by Schweinepriester** [comment]
One could argue that `KeyboardEvent.getModifierState()` should be partial, as @cvrebert noted in [WebKit Bug 162855](https://bugs.webkit.org/show_bug.cgi?id=162855), there are [TODOs left](https://bugs.webkit.org/attachment.cgi?id=290473&action=prettypatch):

```
// FIXME: We should support CapsLock, Fn, FnLock, Hyper, NumLock, Super, ScrollLock, Symbol, SymbolLock.
```

**Comment by Schweinepriester** [comment]
Furthermore I thought about how to handle

> ### URL Handling
- Navigations to tel: and mailto: links now require a user gesture; navigations without a user gesture will show a confirmation prompt
- Users are now prompted when navigating to URLs that open other applications

as <http://caniuse.com/#feat=registerprotocolhandler> shows no support for Safari whatsoever? New issue for adjustment?

**Comment by cvrebert** [comment]
> One could argue that KeyboardEvent.getModifierState() should be partial

Per the discussion in https://bugs.webkit.org/show_bug.cgi?id=162861 , I think it's complete for Mac Safari. And CanIUse understandably doesn't track non-iOS/macOS WebKit.

**Comment by cvrebert** [comment]
Might be worth noting https://bugs.webkit.org/show_bug.cgi?id=162479 in the bugs section of insertAdjacentHTML

**Comment by cvrebert** [comment]
Presumably http://caniuse.com/#feat=classlist was written before `DOMTokenList.supports()` was added  to the spec, given https://trac.webkit.org/changeset/206561/ and the fact that it shows Safari as full green.

**Comment by Fyrd** [comment]
Thanks!

**Comment by Schweinepriester** [comment]
I'll probably create an issue for adjusting URL Handling, how will you proceed @cvrebert?
I do believe its more precise to mention those things :)

**Pull request merged**
