### PR TITLE
Create subresource-integrity

### PR DESCRIPTION
**Pull request by yukulele**

### CODE REVIEW

**Comment by Fyrd** [comment]
@yukulele Thanks, can you add the .json extension to the file? (see the Travis CI info)

**Comment by cvrebert** [comment]
Fixes #1881.

**Comment by yukulele** [comment]
@Fyrd 
done!

**Comment by yukulele** [comment]
fixes #1170

**Comment by Fyrd** [comment]
Thanks!

**Comment by cvrebert** [comment]
@Fyrd Data no longer pending review here.

**Pull request merged**
